#ifndef LL_GLFUNCTIONDECLS_H
#define LL_GLFUNCTIONDECLS_H

// GL_VERSION_1_2
extern PFNGLDRAWRANGEELEMENTSPROC           gGLFunc_glDrawRangeElements;
#define glDrawRangeElements gGLFunc_glDrawRangeElements
extern PFNGLTEXIMAGE3DPROC                  gGLFunc_glTexImage3D;
#define glTexImage3D gGLFunc_glTexImage3D
extern PFNGLTEXSUBIMAGE3DPROC               gGLFunc_glTexSubImage3D;
#define glTexSubImage3D gGLFunc_glTexSubImage3D
extern PFNGLCOPYTEXSUBIMAGE3DPROC           gGLFunc_glCopyTexSubImage3D;
#define glCopyTexSubImage3D gGLFunc_glCopyTexSubImage3D

// GL_VERSION_1_3
extern PFNGLACTIVETEXTUREPROC               gGLFunc_glActiveTexture;
#define glActiveTexture gGLFunc_glActiveTexture
extern PFNGLSAMPLECOVERAGEPROC              gGLFunc_glSampleCoverage;
#define glSampleCoverage gGLFunc_glSampleCoverage
extern PFNGLCOMPRESSEDTEXIMAGE3DPROC        gGLFunc_glCompressedTexImage3D;
#define glCompressedTexImage3D gGLFunc_glCompressedTexImage3D
extern PFNGLCOMPRESSEDTEXIMAGE2DPROC        gGLFunc_glCompressedTexImage2D;
#define glCompressedTexImage2D gGLFunc_glCompressedTexImage2D
extern PFNGLCOMPRESSEDTEXIMAGE1DPROC        gGLFunc_glCompressedTexImage1D;
#define glCompressedTexImage1D gGLFunc_glCompressedTexImage1D
extern PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC     gGLFunc_glCompressedTexSubImage3D;
#define glCompressedTexSubImage3D gGLFunc_glCompressedTexSubImage3D
extern PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC     gGLFunc_glCompressedTexSubImage2D;
#define glCompressedTexSubImage2D gGLFunc_glCompressedTexSubImage2D
extern PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC     gGLFunc_glCompressedTexSubImage1D;
#define glCompressedTexSubImage1D gGLFunc_glCompressedTexSubImage1D
extern PFNGLGETCOMPRESSEDTEXIMAGEPROC       gGLFunc_glGetCompressedTexImage;
#define glGetCompressedTexImage gGLFunc_glGetCompressedTexImage
extern PFNGLCLIENTACTIVETEXTUREPROC         gGLFunc_glClientActiveTexture;
#define glClientActiveTexture gGLFunc_glClientActiveTexture
extern PFNGLMULTITEXCOORD1DPROC             gGLFunc_glMultiTexCoord1d;
#define glMultiTexCoord1d gGLFunc_glMultiTexCoord1d
extern PFNGLMULTITEXCOORD1DVPROC            gGLFunc_glMultiTexCoord1dv;
#define glMultiTexCoord1dv gGLFunc_glMultiTexCoord1dv
extern PFNGLMULTITEXCOORD1FPROC             gGLFunc_glMultiTexCoord1f;
#define glMultiTexCoord1f gGLFunc_glMultiTexCoord1f
extern PFNGLMULTITEXCOORD1FVPROC            gGLFunc_glMultiTexCoord1fv;
#define glMultiTexCoord1fv gGLFunc_glMultiTexCoord1fv
extern PFNGLMULTITEXCOORD1IPROC             gGLFunc_glMultiTexCoord1i;
#define glMultiTexCoord1i gGLFunc_glMultiTexCoord1i
extern PFNGLMULTITEXCOORD1IVPROC            gGLFunc_glMultiTexCoord1iv;
#define glMultiTexCoord1iv gGLFunc_glMultiTexCoord1iv
extern PFNGLMULTITEXCOORD1SPROC             gGLFunc_glMultiTexCoord1s;
#define glMultiTexCoord1s gGLFunc_glMultiTexCoord1s
extern PFNGLMULTITEXCOORD1SVPROC            gGLFunc_glMultiTexCoord1sv;
#define glMultiTexCoord1sv gGLFunc_glMultiTexCoord1sv
extern PFNGLMULTITEXCOORD2DPROC             gGLFunc_glMultiTexCoord2d;
#define glMultiTexCoord2d gGLFunc_glMultiTexCoord2d
extern PFNGLMULTITEXCOORD2DVPROC            gGLFunc_glMultiTexCoord2dv;
#define glMultiTexCoord2dv gGLFunc_glMultiTexCoord2dv
extern PFNGLMULTITEXCOORD2FPROC             gGLFunc_glMultiTexCoord2f;
#define glMultiTexCoord2f gGLFunc_glMultiTexCoord2f
extern PFNGLMULTITEXCOORD2FVPROC            gGLFunc_glMultiTexCoord2fv;
#define glMultiTexCoord2fv gGLFunc_glMultiTexCoord2fv
extern PFNGLMULTITEXCOORD2IPROC             gGLFunc_glMultiTexCoord2i;
#define glMultiTexCoord2i gGLFunc_glMultiTexCoord2i
extern PFNGLMULTITEXCOORD2IVPROC            gGLFunc_glMultiTexCoord2iv;
#define glMultiTexCoord2iv gGLFunc_glMultiTexCoord2iv
extern PFNGLMULTITEXCOORD2SPROC             gGLFunc_glMultiTexCoord2s;
#define glMultiTexCoord2s gGLFunc_glMultiTexCoord2s
extern PFNGLMULTITEXCOORD2SVPROC            gGLFunc_glMultiTexCoord2sv;
#define glMultiTexCoord2sv gGLFunc_glMultiTexCoord2sv
extern PFNGLMULTITEXCOORD3DPROC             gGLFunc_glMultiTexCoord3d;
#define glMultiTexCoord3d gGLFunc_glMultiTexCoord3d
extern PFNGLMULTITEXCOORD3DVPROC            gGLFunc_glMultiTexCoord3dv;
#define glMultiTexCoord3dv gGLFunc_glMultiTexCoord3dv
extern PFNGLMULTITEXCOORD3FPROC             gGLFunc_glMultiTexCoord3f;
#define glMultiTexCoord3f gGLFunc_glMultiTexCoord3f
extern PFNGLMULTITEXCOORD3FVPROC            gGLFunc_glMultiTexCoord3fv;
#define glMultiTexCoord3fv gGLFunc_glMultiTexCoord3fv
extern PFNGLMULTITEXCOORD3IPROC             gGLFunc_glMultiTexCoord3i;
#define glMultiTexCoord3i gGLFunc_glMultiTexCoord3i
extern PFNGLMULTITEXCOORD3IVPROC            gGLFunc_glMultiTexCoord3iv;
#define glMultiTexCoord3iv gGLFunc_glMultiTexCoord3iv
extern PFNGLMULTITEXCOORD3SPROC             gGLFunc_glMultiTexCoord3s;
#define glMultiTexCoord3s gGLFunc_glMultiTexCoord3s
extern PFNGLMULTITEXCOORD3SVPROC            gGLFunc_glMultiTexCoord3sv;
#define glMultiTexCoord3sv gGLFunc_glMultiTexCoord3sv
extern PFNGLMULTITEXCOORD4DPROC             gGLFunc_glMultiTexCoord4d;
#define glMultiTexCoord4d gGLFunc_glMultiTexCoord4d
extern PFNGLMULTITEXCOORD4DVPROC            gGLFunc_glMultiTexCoord4dv;
#define glMultiTexCoord4dv gGLFunc_glMultiTexCoord4dv
extern PFNGLMULTITEXCOORD4FPROC             gGLFunc_glMultiTexCoord4f;
#define glMultiTexCoord4f gGLFunc_glMultiTexCoord4f
extern PFNGLMULTITEXCOORD4FVPROC            gGLFunc_glMultiTexCoord4fv;
#define glMultiTexCoord4fv gGLFunc_glMultiTexCoord4fv
extern PFNGLMULTITEXCOORD4IPROC             gGLFunc_glMultiTexCoord4i;
#define glMultiTexCoord4i gGLFunc_glMultiTexCoord4i
extern PFNGLMULTITEXCOORD4IVPROC            gGLFunc_glMultiTexCoord4iv;
#define glMultiTexCoord4iv gGLFunc_glMultiTexCoord4iv
extern PFNGLMULTITEXCOORD4SPROC             gGLFunc_glMultiTexCoord4s;
#define glMultiTexCoord4s gGLFunc_glMultiTexCoord4s
extern PFNGLMULTITEXCOORD4SVPROC            gGLFunc_glMultiTexCoord4sv;
#define glMultiTexCoord4sv gGLFunc_glMultiTexCoord4sv
extern PFNGLLOADTRANSPOSEMATRIXFPROC        gGLFunc_glLoadTransposeMatrixf;
#define glLoadTransposeMatrixf gGLFunc_glLoadTransposeMatrixf
extern PFNGLLOADTRANSPOSEMATRIXDPROC        gGLFunc_glLoadTransposeMatrixd;
#define glLoadTransposeMatrixd gGLFunc_glLoadTransposeMatrixd
extern PFNGLMULTTRANSPOSEMATRIXFPROC        gGLFunc_glMultTransposeMatrixf;
#define glMultTransposeMatrixf gGLFunc_glMultTransposeMatrixf
extern PFNGLMULTTRANSPOSEMATRIXDPROC        gGLFunc_glMultTransposeMatrixd;
#define glMultTransposeMatrixd gGLFunc_glMultTransposeMatrixd

// GL_VERSION_1_4
extern PFNGLBLENDFUNCSEPARATEPROC       gGLFunc_glBlendFuncSeparate;
#define glBlendFuncSeparate gGLFunc_glBlendFuncSeparate
extern PFNGLMULTIDRAWARRAYSPROC         gGLFunc_glMultiDrawArrays;
#define glMultiDrawArrays gGLFunc_glMultiDrawArrays
extern PFNGLMULTIDRAWELEMENTSPROC       gGLFunc_glMultiDrawElements;
#define glMultiDrawElements gGLFunc_glMultiDrawElements
extern PFNGLPOINTPARAMETERFPROC         gGLFunc_glPointParameterf;
#define glPointParameterf gGLFunc_glPointParameterf
extern PFNGLPOINTPARAMETERFVPROC        gGLFunc_glPointParameterfv;
#define glPointParameterfv gGLFunc_glPointParameterfv
extern PFNGLPOINTPARAMETERIPROC         gGLFunc_glPointParameteri;
#define glPointParameteri gGLFunc_glPointParameteri
extern PFNGLPOINTPARAMETERIVPROC        gGLFunc_glPointParameteriv;
#define glPointParameteriv gGLFunc_glPointParameteriv
extern PFNGLFOGCOORDFPROC               gGLFunc_glFogCoordf;
#define glFogCoordf gGLFunc_glFogCoordf
extern PFNGLFOGCOORDFVPROC              gGLFunc_glFogCoordfv;
#define glFogCoordfv gGLFunc_glFogCoordfv
extern PFNGLFOGCOORDDPROC               gGLFunc_glFogCoordd;
#define glFogCoordd gGLFunc_glFogCoordd
extern PFNGLFOGCOORDDVPROC              gGLFunc_glFogCoorddv;
#define glFogCoorddv gGLFunc_glFogCoorddv
extern PFNGLFOGCOORDPOINTERPROC         gGLFunc_glFogCoordPointer;
#define glFogCoordPointer gGLFunc_glFogCoordPointer
extern PFNGLSECONDARYCOLOR3BPROC        gGLFunc_glSecondaryColor3b;
#define glSecondaryColor3b gGLFunc_glSecondaryColor3b
extern PFNGLSECONDARYCOLOR3BVPROC       gGLFunc_glSecondaryColor3bv;
#define glSecondaryColor3bv gGLFunc_glSecondaryColor3bv
extern PFNGLSECONDARYCOLOR3DPROC        gGLFunc_glSecondaryColor3d;
#define glSecondaryColor3d gGLFunc_glSecondaryColor3d
extern PFNGLSECONDARYCOLOR3DVPROC       gGLFunc_glSecondaryColor3dv;
#define glSecondaryColor3dv gGLFunc_glSecondaryColor3dv
extern PFNGLSECONDARYCOLOR3FPROC        gGLFunc_glSecondaryColor3f;
#define glSecondaryColor3f gGLFunc_glSecondaryColor3f
extern PFNGLSECONDARYCOLOR3FVPROC       gGLFunc_glSecondaryColor3fv;
#define glSecondaryColor3fv gGLFunc_glSecondaryColor3fv
extern PFNGLSECONDARYCOLOR3IPROC        gGLFunc_glSecondaryColor3i;
#define glSecondaryColor3i gGLFunc_glSecondaryColor3i
extern PFNGLSECONDARYCOLOR3IVPROC       gGLFunc_glSecondaryColor3iv;
#define glSecondaryColor3iv gGLFunc_glSecondaryColor3iv
extern PFNGLSECONDARYCOLOR3SPROC        gGLFunc_glSecondaryColor3s;
#define glSecondaryColor3s gGLFunc_glSecondaryColor3s
extern PFNGLSECONDARYCOLOR3SVPROC       gGLFunc_glSecondaryColor3sv;
#define glSecondaryColor3sv gGLFunc_glSecondaryColor3sv
extern PFNGLSECONDARYCOLOR3UBPROC       gGLFunc_glSecondaryColor3ub;
#define glSecondaryColor3ub gGLFunc_glSecondaryColor3ub
extern PFNGLSECONDARYCOLOR3UBVPROC      gGLFunc_glSecondaryColor3ubv;
#define glSecondaryColor3ubv gGLFunc_glSecondaryColor3ubv
extern PFNGLSECONDARYCOLOR3UIPROC       gGLFunc_glSecondaryColor3ui;
#define glSecondaryColor3ui gGLFunc_glSecondaryColor3ui
extern PFNGLSECONDARYCOLOR3UIVPROC      gGLFunc_glSecondaryColor3uiv;
#define glSecondaryColor3uiv gGLFunc_glSecondaryColor3uiv
extern PFNGLSECONDARYCOLOR3USPROC       gGLFunc_glSecondaryColor3us;
#define glSecondaryColor3us gGLFunc_glSecondaryColor3us
extern PFNGLSECONDARYCOLOR3USVPROC      gGLFunc_glSecondaryColor3usv;
#define glSecondaryColor3usv gGLFunc_glSecondaryColor3usv
extern PFNGLSECONDARYCOLORPOINTERPROC   gGLFunc_glSecondaryColorPointer;
#define glSecondaryColorPointer gGLFunc_glSecondaryColorPointer
extern PFNGLWINDOWPOS2DPROC             gGLFunc_glWindowPos2d;
#define glWindowPos2d gGLFunc_glWindowPos2d
extern PFNGLWINDOWPOS2DVPROC            gGLFunc_glWindowPos2dv;
#define glWindowPos2dv gGLFunc_glWindowPos2dv
extern PFNGLWINDOWPOS2FPROC             gGLFunc_glWindowPos2f;
#define glWindowPos2f gGLFunc_glWindowPos2f
extern PFNGLWINDOWPOS2FVPROC            gGLFunc_glWindowPos2fv;
#define glWindowPos2fv gGLFunc_glWindowPos2fv
extern PFNGLWINDOWPOS2IPROC             gGLFunc_glWindowPos2i;
#define glWindowPos2i gGLFunc_glWindowPos2i
extern PFNGLWINDOWPOS2IVPROC            gGLFunc_glWindowPos2iv;
#define glWindowPos2iv gGLFunc_glWindowPos2iv
extern PFNGLWINDOWPOS2SPROC             gGLFunc_glWindowPos2s;
#define glWindowPos2s gGLFunc_glWindowPos2s
extern PFNGLWINDOWPOS2SVPROC            gGLFunc_glWindowPos2sv;
#define glWindowPos2sv gGLFunc_glWindowPos2sv
extern PFNGLWINDOWPOS3DPROC             gGLFunc_glWindowPos3d;
#define glWindowPos3d gGLFunc_glWindowPos3d
extern PFNGLWINDOWPOS3DVPROC            gGLFunc_glWindowPos3dv;
#define glWindowPos3dv gGLFunc_glWindowPos3dv
extern PFNGLWINDOWPOS3FPROC             gGLFunc_glWindowPos3f;
#define glWindowPos3f gGLFunc_glWindowPos3f
extern PFNGLWINDOWPOS3FVPROC            gGLFunc_glWindowPos3fv;
#define glWindowPos3fv gGLFunc_glWindowPos3fv
extern PFNGLWINDOWPOS3IPROC             gGLFunc_glWindowPos3i;
#define glWindowPos3i gGLFunc_glWindowPos3i
extern PFNGLWINDOWPOS3IVPROC            gGLFunc_glWindowPos3iv;
#define glWindowPos3iv gGLFunc_glWindowPos3iv
extern PFNGLWINDOWPOS3SPROC             gGLFunc_glWindowPos3s;
#define glWindowPos3s gGLFunc_glWindowPos3s
extern PFNGLWINDOWPOS3SVPROC            gGLFunc_glWindowPos3sv;
#define glWindowPos3sv gGLFunc_glWindowPos3sv

// GL_VERSION_1_5
extern PFNGLGENQUERIESPROC              gGLFunc_glGenQueries;
#define glGenQueries gGLFunc_glGenQueries
extern PFNGLDELETEQUERIESPROC           gGLFunc_glDeleteQueries;
#define glDeleteQueries gGLFunc_glDeleteQueries
extern PFNGLISQUERYPROC                 gGLFunc_glIsQuery;
#define glIsQuery gGLFunc_glIsQuery
extern PFNGLBEGINQUERYPROC              gGLFunc_glBeginQuery;
#define glBeginQuery gGLFunc_glBeginQuery
extern PFNGLENDQUERYPROC                gGLFunc_glEndQuery;
#define glEndQuery gGLFunc_glEndQuery
extern PFNGLGETQUERYIVPROC              gGLFunc_glGetQueryiv;
#define glGetQueryiv gGLFunc_glGetQueryiv
extern PFNGLGETQUERYOBJECTIVPROC        gGLFunc_glGetQueryObjectiv;
#define glGetQueryObjectiv gGLFunc_glGetQueryObjectiv
extern PFNGLGETQUERYOBJECTUIVPROC       gGLFunc_glGetQueryObjectuiv;
#define glGetQueryObjectuiv gGLFunc_glGetQueryObjectuiv
extern PFNGLBINDBUFFERPROC              gGLFunc_glBindBuffer;
#define glBindBuffer gGLFunc_glBindBuffer
extern PFNGLDELETEBUFFERSPROC           gGLFunc_glDeleteBuffers;
#define glDeleteBuffers gGLFunc_glDeleteBuffers
extern PFNGLGENBUFFERSPROC              gGLFunc_glGenBuffers;
#define glGenBuffers gGLFunc_glGenBuffers
extern PFNGLISBUFFERPROC                gGLFunc_glIsBuffer;
#define glIsBuffer gGLFunc_glIsBuffer
extern PFNGLBUFFERDATAPROC              gGLFunc_glBufferData;
#define glBufferData gGLFunc_glBufferData
extern PFNGLBUFFERSUBDATAPROC           gGLFunc_glBufferSubData;
#define glBufferSubData gGLFunc_glBufferSubData
extern PFNGLGETBUFFERSUBDATAPROC        gGLFunc_glGetBufferSubData;
#define glGetBufferSubData gGLFunc_glGetBufferSubData
extern PFNGLMAPBUFFERPROC               gGLFunc_glMapBuffer;
#define glMapBuffer gGLFunc_glMapBuffer
extern PFNGLUNMAPBUFFERPROC             gGLFunc_glUnmapBuffer;
#define glUnmapBuffer gGLFunc_glUnmapBuffer
extern PFNGLGETBUFFERPARAMETERIVPROC    gGLFunc_glGetBufferParameteriv;
#define glGetBufferParameteriv gGLFunc_glGetBufferParameteriv
extern PFNGLGETBUFFERPOINTERVPROC       gGLFunc_glGetBufferPointerv;
#define glGetBufferPointerv gGLFunc_glGetBufferPointerv

// GL_VERSION_2_0
extern PFNGLBLENDEQUATIONSEPARATEPROC           gGLFunc_glBlendEquationSeparate;
#define glBlendEquationSeparate gGLFunc_glBlendEquationSeparate
extern PFNGLDRAWBUFFERSPROC                     gGLFunc_glDrawBuffers;
#define glDrawBuffers gGLFunc_glDrawBuffers
extern PFNGLSTENCILOPSEPARATEPROC               gGLFunc_glStencilOpSeparate;
#define glStencilOpSeparate gGLFunc_glStencilOpSeparate
extern PFNGLSTENCILFUNCSEPARATEPROC             gGLFunc_glStencilFuncSeparate;
#define glStencilFuncSeparate gGLFunc_glStencilFuncSeparate
extern PFNGLSTENCILMASKSEPARATEPROC             gGLFunc_glStencilMaskSeparate;
#define glStencilMaskSeparate gGLFunc_glStencilMaskSeparate
extern PFNGLATTACHSHADERPROC                    gGLFunc_glAttachShader;
#define glAttachShader gGLFunc_glAttachShader
extern PFNGLBINDATTRIBLOCATIONPROC              gGLFunc_glBindAttribLocation;
#define glBindAttribLocation gGLFunc_glBindAttribLocation
extern PFNGLCOMPILESHADERPROC                   gGLFunc_glCompileShader;
#define glCompileShader gGLFunc_glCompileShader
extern PFNGLCREATEPROGRAMPROC                   gGLFunc_glCreateProgram;
#define glCreateProgram gGLFunc_glCreateProgram
extern PFNGLCREATESHADERPROC                    gGLFunc_glCreateShader;
#define glCreateShader gGLFunc_glCreateShader
extern PFNGLDELETEPROGRAMPROC                   gGLFunc_glDeleteProgram;
#define glDeleteProgram gGLFunc_glDeleteProgram
extern PFNGLDELETESHADERPROC                    gGLFunc_glDeleteShader;
#define glDeleteShader gGLFunc_glDeleteShader
extern PFNGLDETACHSHADERPROC                    gGLFunc_glDetachShader;
#define glDetachShader gGLFunc_glDetachShader
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC        gGLFunc_glDisableVertexAttribArray;
#define glDisableVertexAttribArray gGLFunc_glDisableVertexAttribArray
extern PFNGLENABLEVERTEXATTRIBARRAYPROC         gGLFunc_glEnableVertexAttribArray;
#define glEnableVertexAttribArray gGLFunc_glEnableVertexAttribArray
extern PFNGLGETACTIVEATTRIBPROC                 gGLFunc_glGetActiveAttrib;
#define glGetActiveAttrib gGLFunc_glGetActiveAttrib
extern PFNGLGETACTIVEUNIFORMPROC                gGLFunc_glGetActiveUniform;
#define glGetActiveUniform gGLFunc_glGetActiveUniform
extern PFNGLGETATTACHEDSHADERSPROC              gGLFunc_glGetAttachedShaders;
#define glGetAttachedShaders gGLFunc_glGetAttachedShaders
extern PFNGLGETATTRIBLOCATIONPROC               gGLFunc_glGetAttribLocation;
#define glGetAttribLocation gGLFunc_glGetAttribLocation
extern PFNGLGETPROGRAMIVPROC                    gGLFunc_glGetProgramiv;
#define glGetProgramiv gGLFunc_glGetProgramiv
extern PFNGLGETPROGRAMINFOLOGPROC               gGLFunc_glGetProgramInfoLog;
#define glGetProgramInfoLog gGLFunc_glGetProgramInfoLog
extern PFNGLGETSHADERIVPROC                     gGLFunc_glGetShaderiv;
#define glGetShaderiv gGLFunc_glGetShaderiv
extern PFNGLGETSHADERINFOLOGPROC                gGLFunc_glGetShaderInfoLog;
#define glGetShaderInfoLog gGLFunc_glGetShaderInfoLog
extern PFNGLGETSHADERSOURCEPROC                 gGLFunc_glGetShaderSource;
#define glGetShaderSource gGLFunc_glGetShaderSource
extern PFNGLGETUNIFORMLOCATIONPROC              gGLFunc_glGetUniformLocation;
#define glGetUniformLocation gGLFunc_glGetUniformLocation
extern PFNGLGETUNIFORMFVPROC                    gGLFunc_glGetUniformfv;
#define glGetUniformfv gGLFunc_glGetUniformfv
extern PFNGLGETUNIFORMIVPROC                    gGLFunc_glGetUniformiv;
#define glGetUniformiv gGLFunc_glGetUniformiv
extern PFNGLGETVERTEXATTRIBDVPROC               gGLFunc_glGetVertexAttribdv;
#define glGetVertexAttribdv gGLFunc_glGetVertexAttribdv
extern PFNGLGETVERTEXATTRIBFVPROC               gGLFunc_glGetVertexAttribfv;
#define glGetVertexAttribfv gGLFunc_glGetVertexAttribfv
extern PFNGLGETVERTEXATTRIBIVPROC               gGLFunc_glGetVertexAttribiv;
#define glGetVertexAttribiv gGLFunc_glGetVertexAttribiv
extern PFNGLGETVERTEXATTRIBPOINTERVPROC         gGLFunc_glGetVertexAttribPointerv;
#define glGetVertexAttribPointerv gGLFunc_glGetVertexAttribPointerv
extern PFNGLISPROGRAMPROC                       gGLFunc_glIsProgram;
#define glIsProgram gGLFunc_glIsProgram
extern PFNGLISSHADERPROC                        gGLFunc_glIsShader;
#define glIsShader gGLFunc_glIsShader
extern PFNGLLINKPROGRAMPROC                     gGLFunc_glLinkProgram;
#define glLinkProgram gGLFunc_glLinkProgram
extern PFNGLSHADERSOURCEPROC                    gGLFunc_glShaderSource;
#define glShaderSource gGLFunc_glShaderSource
extern PFNGLUSEPROGRAMPROC                      gGLFunc_glUseProgram;
#define glUseProgram gGLFunc_glUseProgram
extern PFNGLUNIFORM1FPROC                       gGLFunc_glUniform1f;
#define glUniform1f gGLFunc_glUniform1f
extern PFNGLUNIFORM2FPROC                       gGLFunc_glUniform2f;
#define glUniform2f gGLFunc_glUniform2f
extern PFNGLUNIFORM3FPROC                       gGLFunc_glUniform3f;
#define glUniform3f gGLFunc_glUniform3f
extern PFNGLUNIFORM4FPROC                       gGLFunc_glUniform4f;
#define glUniform4f gGLFunc_glUniform4f
extern PFNGLUNIFORM1IPROC                       gGLFunc_glUniform1i;
#define glUniform1i gGLFunc_glUniform1i
extern PFNGLUNIFORM2IPROC                       gGLFunc_glUniform2i;
#define glUniform2i gGLFunc_glUniform2i
extern PFNGLUNIFORM3IPROC                       gGLFunc_glUniform3i;
#define glUniform3i gGLFunc_glUniform3i
extern PFNGLUNIFORM4IPROC                       gGLFunc_glUniform4i;
#define glUniform4i gGLFunc_glUniform4i
extern PFNGLUNIFORM1FVPROC                      gGLFunc_glUniform1fv;
#define glUniform1fv gGLFunc_glUniform1fv
extern PFNGLUNIFORM2FVPROC                      gGLFunc_glUniform2fv;
#define glUniform2fv gGLFunc_glUniform2fv
extern PFNGLUNIFORM3FVPROC                      gGLFunc_glUniform3fv;
#define glUniform3fv gGLFunc_glUniform3fv
extern PFNGLUNIFORM4FVPROC                      gGLFunc_glUniform4fv;
#define glUniform4fv gGLFunc_glUniform4fv
extern PFNGLUNIFORM1IVPROC                      gGLFunc_glUniform1iv;
#define glUniform1iv gGLFunc_glUniform1iv
extern PFNGLUNIFORM2IVPROC                      gGLFunc_glUniform2iv;
#define glUniform2iv gGLFunc_glUniform2iv
extern PFNGLUNIFORM3IVPROC                      gGLFunc_glUniform3iv;
#define glUniform3iv gGLFunc_glUniform3iv
extern PFNGLUNIFORM4IVPROC                      gGLFunc_glUniform4iv;
#define glUniform4iv gGLFunc_glUniform4iv
extern PFNGLUNIFORMMATRIX2FVPROC                gGLFunc_glUniformMatrix2fv;
#define glUniformMatrix2fv gGLFunc_glUniformMatrix2fv
extern PFNGLUNIFORMMATRIX3FVPROC                gGLFunc_glUniformMatrix3fv;
#define glUniformMatrix3fv gGLFunc_glUniformMatrix3fv
extern PFNGLUNIFORMMATRIX4FVPROC                gGLFunc_glUniformMatrix4fv;
#define glUniformMatrix4fv gGLFunc_glUniformMatrix4fv
extern PFNGLVALIDATEPROGRAMPROC                 gGLFunc_glValidateProgram;
#define glValidateProgram gGLFunc_glValidateProgram
extern PFNGLVERTEXATTRIB1DPROC                  gGLFunc_glVertexAttrib1d;
#define glVertexAttrib1d gGLFunc_glVertexAttrib1d
extern PFNGLVERTEXATTRIB1DVPROC                 gGLFunc_glVertexAttrib1dv;
#define glVertexAttrib1dv gGLFunc_glVertexAttrib1dv
extern PFNGLVERTEXATTRIB1FPROC                  gGLFunc_glVertexAttrib1f;
#define glVertexAttrib1f gGLFunc_glVertexAttrib1f
extern PFNGLVERTEXATTRIB1FVPROC                 gGLFunc_glVertexAttrib1fv;
#define glVertexAttrib1fv gGLFunc_glVertexAttrib1fv
extern PFNGLVERTEXATTRIB1SPROC                  gGLFunc_glVertexAttrib1s;
#define glVertexAttrib1s gGLFunc_glVertexAttrib1s
extern PFNGLVERTEXATTRIB1SVPROC                 gGLFunc_glVertexAttrib1sv;
#define glVertexAttrib1sv gGLFunc_glVertexAttrib1sv
extern PFNGLVERTEXATTRIB2DPROC                  gGLFunc_glVertexAttrib2d;
#define glVertexAttrib2d gGLFunc_glVertexAttrib2d
extern PFNGLVERTEXATTRIB2DVPROC                 gGLFunc_glVertexAttrib2dv;
#define glVertexAttrib2dv gGLFunc_glVertexAttrib2dv
extern PFNGLVERTEXATTRIB2FPROC                  gGLFunc_glVertexAttrib2f;
#define glVertexAttrib2f gGLFunc_glVertexAttrib2f
extern PFNGLVERTEXATTRIB2FVPROC                 gGLFunc_glVertexAttrib2fv;
#define glVertexAttrib2fv gGLFunc_glVertexAttrib2fv
extern PFNGLVERTEXATTRIB2SPROC                  gGLFunc_glVertexAttrib2s;
#define glVertexAttrib2s gGLFunc_glVertexAttrib2s
extern PFNGLVERTEXATTRIB2SVPROC                 gGLFunc_glVertexAttrib2sv;
#define glVertexAttrib2sv gGLFunc_glVertexAttrib2sv
extern PFNGLVERTEXATTRIB3DPROC                  gGLFunc_glVertexAttrib3d;
#define glVertexAttrib3d gGLFunc_glVertexAttrib3d
extern PFNGLVERTEXATTRIB3DVPROC                 gGLFunc_glVertexAttrib3dv;
#define glVertexAttrib3dv gGLFunc_glVertexAttrib3dv
extern PFNGLVERTEXATTRIB3FPROC                  gGLFunc_glVertexAttrib3f;
#define glVertexAttrib3f gGLFunc_glVertexAttrib3f
extern PFNGLVERTEXATTRIB3FVPROC                 gGLFunc_glVertexAttrib3fv;
#define glVertexAttrib3fv gGLFunc_glVertexAttrib3fv
extern PFNGLVERTEXATTRIB3SPROC                  gGLFunc_glVertexAttrib3s;
#define glVertexAttrib3s gGLFunc_glVertexAttrib3s
extern PFNGLVERTEXATTRIB3SVPROC                 gGLFunc_glVertexAttrib3sv;
#define glVertexAttrib3sv gGLFunc_glVertexAttrib3sv
extern PFNGLVERTEXATTRIB4NBVPROC                gGLFunc_glVertexAttrib4Nbv;
#define glVertexAttrib4Nbv gGLFunc_glVertexAttrib4Nbv
extern PFNGLVERTEXATTRIB4NIVPROC                gGLFunc_glVertexAttrib4Niv;
#define glVertexAttrib4Niv gGLFunc_glVertexAttrib4Niv
extern PFNGLVERTEXATTRIB4NSVPROC                gGLFunc_glVertexAttrib4Nsv;
#define glVertexAttrib4Nsv gGLFunc_glVertexAttrib4Nsv
extern PFNGLVERTEXATTRIB4NUBPROC                gGLFunc_glVertexAttrib4Nub;
#define glVertexAttrib4Nub gGLFunc_glVertexAttrib4Nub
extern PFNGLVERTEXATTRIB4NUBVPROC               gGLFunc_glVertexAttrib4Nubv;
#define glVertexAttrib4Nubv gGLFunc_glVertexAttrib4Nubv
extern PFNGLVERTEXATTRIB4NUIVPROC               gGLFunc_glVertexAttrib4Nuiv;
#define glVertexAttrib4Nuiv gGLFunc_glVertexAttrib4Nuiv
extern PFNGLVERTEXATTRIB4NUSVPROC               gGLFunc_glVertexAttrib4Nusv;
#define glVertexAttrib4Nusv gGLFunc_glVertexAttrib4Nusv
extern PFNGLVERTEXATTRIB4BVPROC                 gGLFunc_glVertexAttrib4bv;
#define glVertexAttrib4bv gGLFunc_glVertexAttrib4bv
extern PFNGLVERTEXATTRIB4DPROC                  gGLFunc_glVertexAttrib4d;
#define glVertexAttrib4d gGLFunc_glVertexAttrib4d
extern PFNGLVERTEXATTRIB4DVPROC                 gGLFunc_glVertexAttrib4dv;
#define glVertexAttrib4dv gGLFunc_glVertexAttrib4dv
extern PFNGLVERTEXATTRIB4FPROC                  gGLFunc_glVertexAttrib4f;
#define glVertexAttrib4f gGLFunc_glVertexAttrib4f
extern PFNGLVERTEXATTRIB4FVPROC                 gGLFunc_glVertexAttrib4fv;
#define glVertexAttrib4fv gGLFunc_glVertexAttrib4fv
extern PFNGLVERTEXATTRIB4IVPROC                 gGLFunc_glVertexAttrib4iv;
#define glVertexAttrib4iv gGLFunc_glVertexAttrib4iv
extern PFNGLVERTEXATTRIB4SPROC                  gGLFunc_glVertexAttrib4s;
#define glVertexAttrib4s gGLFunc_glVertexAttrib4s
extern PFNGLVERTEXATTRIB4SVPROC                 gGLFunc_glVertexAttrib4sv;
#define glVertexAttrib4sv gGLFunc_glVertexAttrib4sv
extern PFNGLVERTEXATTRIB4UBVPROC                gGLFunc_glVertexAttrib4ubv;
#define glVertexAttrib4ubv gGLFunc_glVertexAttrib4ubv
extern PFNGLVERTEXATTRIB4UIVPROC                gGLFunc_glVertexAttrib4uiv;
#define glVertexAttrib4uiv gGLFunc_glVertexAttrib4uiv
extern PFNGLVERTEXATTRIB4USVPROC                gGLFunc_glVertexAttrib4usv;
#define glVertexAttrib4usv gGLFunc_glVertexAttrib4usv
extern PFNGLVERTEXATTRIBPOINTERPROC             gGLFunc_glVertexAttribPointer;
#define glVertexAttribPointer gGLFunc_glVertexAttribPointer

// GL_VERSION_2_1
extern PFNGLUNIFORMMATRIX2X3FVPROC gGLFunc_glUniformMatrix2x3fv;
#define glUniformMatrix2x3fv gGLFunc_glUniformMatrix2x3fv
extern PFNGLUNIFORMMATRIX3X2FVPROC gGLFunc_glUniformMatrix3x2fv;
#define glUniformMatrix3x2fv gGLFunc_glUniformMatrix3x2fv
extern PFNGLUNIFORMMATRIX2X4FVPROC gGLFunc_glUniformMatrix2x4fv;
#define glUniformMatrix2x4fv gGLFunc_glUniformMatrix2x4fv
extern PFNGLUNIFORMMATRIX4X2FVPROC gGLFunc_glUniformMatrix4x2fv;
#define glUniformMatrix4x2fv gGLFunc_glUniformMatrix4x2fv
extern PFNGLUNIFORMMATRIX3X4FVPROC gGLFunc_glUniformMatrix3x4fv;
#define glUniformMatrix3x4fv gGLFunc_glUniformMatrix3x4fv
extern PFNGLUNIFORMMATRIX4X3FVPROC gGLFunc_glUniformMatrix4x3fv;
#define glUniformMatrix4x3fv gGLFunc_glUniformMatrix4x3fv

// GL_VERSION_3_0
extern PFNGLCOLORMASKIPROC                              gGLFunc_glColorMaski;
#define glColorMaski gGLFunc_glColorMaski
extern PFNGLGETBOOLEANI_VPROC                           gGLFunc_glGetBooleani_v;
#define glGetBooleani_v gGLFunc_glGetBooleani_v
extern PFNGLGETINTEGERI_VPROC                           gGLFunc_glGetIntegeri_v;
#define glGetIntegeri_v gGLFunc_glGetIntegeri_v
extern PFNGLENABLEIPROC                                 gGLFunc_glEnablei;
#define glEnablei gGLFunc_glEnablei
extern PFNGLDISABLEIPROC                                gGLFunc_glDisablei;
#define glDisablei gGLFunc_glDisablei
extern PFNGLISENABLEDIPROC                              gGLFunc_glIsEnabledi;
#define glIsEnabledi gGLFunc_glIsEnabledi
extern PFNGLBEGINTRANSFORMFEEDBACKPROC                  gGLFunc_glBeginTransformFeedback;
#define glBeginTransformFeedback gGLFunc_glBeginTransformFeedback
extern PFNGLENDTRANSFORMFEEDBACKPROC                    gGLFunc_glEndTransformFeedback;
#define glEndTransformFeedback gGLFunc_glEndTransformFeedback
extern PFNGLBINDBUFFERRANGEPROC                         gGLFunc_glBindBufferRange;
#define glBindBufferRange gGLFunc_glBindBufferRange
extern PFNGLBINDBUFFERBASEPROC                          gGLFunc_glBindBufferBase;
#define glBindBufferBase gGLFunc_glBindBufferBase
extern PFNGLTRANSFORMFEEDBACKVARYINGSPROC               gGLFunc_glTransformFeedbackVaryings;
#define glTransformFeedbackVaryings gGLFunc_glTransformFeedbackVaryings
extern PFNGLGETTRANSFORMFEEDBACKVARYINGPROC             gGLFunc_glGetTransformFeedbackVarying;
#define glGetTransformFeedbackVarying gGLFunc_glGetTransformFeedbackVarying
extern PFNGLCLAMPCOLORPROC                              gGLFunc_glClampColor;
#define glClampColor gGLFunc_glClampColor
extern PFNGLBEGINCONDITIONALRENDERPROC                  gGLFunc_glBeginConditionalRender;
#define glBeginConditionalRender gGLFunc_glBeginConditionalRender
extern PFNGLENDCONDITIONALRENDERPROC                    gGLFunc_glEndConditionalRender;
#define glEndConditionalRender gGLFunc_glEndConditionalRender
extern PFNGLVERTEXATTRIBIPOINTERPROC                    gGLFunc_glVertexAttribIPointer;
#define glVertexAttribIPointer gGLFunc_glVertexAttribIPointer
extern PFNGLGETVERTEXATTRIBIIVPROC                      gGLFunc_glGetVertexAttribIiv;
#define glGetVertexAttribIiv gGLFunc_glGetVertexAttribIiv
extern PFNGLGETVERTEXATTRIBIUIVPROC                     gGLFunc_glGetVertexAttribIuiv;
#define glGetVertexAttribIuiv gGLFunc_glGetVertexAttribIuiv
extern PFNGLVERTEXATTRIBI1IPROC                         gGLFunc_glVertexAttribI1i;
#define glVertexAttribI1i gGLFunc_glVertexAttribI1i
extern PFNGLVERTEXATTRIBI2IPROC                         gGLFunc_glVertexAttribI2i;
#define glVertexAttribI2i gGLFunc_glVertexAttribI2i
extern PFNGLVERTEXATTRIBI3IPROC                         gGLFunc_glVertexAttribI3i;
#define glVertexAttribI3i gGLFunc_glVertexAttribI3i
extern PFNGLVERTEXATTRIBI4IPROC                         gGLFunc_glVertexAttribI4i;
#define glVertexAttribI4i gGLFunc_glVertexAttribI4i
extern PFNGLVERTEXATTRIBI1UIPROC                        gGLFunc_glVertexAttribI1ui;
#define glVertexAttribI1ui gGLFunc_glVertexAttribI1ui
extern PFNGLVERTEXATTRIBI2UIPROC                        gGLFunc_glVertexAttribI2ui;
#define glVertexAttribI2ui gGLFunc_glVertexAttribI2ui
extern PFNGLVERTEXATTRIBI3UIPROC                        gGLFunc_glVertexAttribI3ui;
#define glVertexAttribI3ui gGLFunc_glVertexAttribI3ui
extern PFNGLVERTEXATTRIBI4UIPROC                        gGLFunc_glVertexAttribI4ui;
#define glVertexAttribI4ui gGLFunc_glVertexAttribI4ui
extern PFNGLVERTEXATTRIBI1IVPROC                        gGLFunc_glVertexAttribI1iv;
#define glVertexAttribI1iv gGLFunc_glVertexAttribI1iv
extern PFNGLVERTEXATTRIBI2IVPROC                        gGLFunc_glVertexAttribI2iv;
#define glVertexAttribI2iv gGLFunc_glVertexAttribI2iv
extern PFNGLVERTEXATTRIBI3IVPROC                        gGLFunc_glVertexAttribI3iv;
#define glVertexAttribI3iv gGLFunc_glVertexAttribI3iv
extern PFNGLVERTEXATTRIBI4IVPROC                        gGLFunc_glVertexAttribI4iv;
#define glVertexAttribI4iv gGLFunc_glVertexAttribI4iv
extern PFNGLVERTEXATTRIBI1UIVPROC                       gGLFunc_glVertexAttribI1uiv;
#define glVertexAttribI1uiv gGLFunc_glVertexAttribI1uiv
extern PFNGLVERTEXATTRIBI2UIVPROC                       gGLFunc_glVertexAttribI2uiv;
#define glVertexAttribI2uiv gGLFunc_glVertexAttribI2uiv
extern PFNGLVERTEXATTRIBI3UIVPROC                       gGLFunc_glVertexAttribI3uiv;
#define glVertexAttribI3uiv gGLFunc_glVertexAttribI3uiv
extern PFNGLVERTEXATTRIBI4UIVPROC                       gGLFunc_glVertexAttribI4uiv;
#define glVertexAttribI4uiv gGLFunc_glVertexAttribI4uiv
extern PFNGLVERTEXATTRIBI4BVPROC                        gGLFunc_glVertexAttribI4bv;
#define glVertexAttribI4bv gGLFunc_glVertexAttribI4bv
extern PFNGLVERTEXATTRIBI4SVPROC                        gGLFunc_glVertexAttribI4sv;
#define glVertexAttribI4sv gGLFunc_glVertexAttribI4sv
extern PFNGLVERTEXATTRIBI4UBVPROC                       gGLFunc_glVertexAttribI4ubv;
#define glVertexAttribI4ubv gGLFunc_glVertexAttribI4ubv
extern PFNGLVERTEXATTRIBI4USVPROC                       gGLFunc_glVertexAttribI4usv;
#define glVertexAttribI4usv gGLFunc_glVertexAttribI4usv
extern PFNGLGETUNIFORMUIVPROC                           gGLFunc_glGetUniformuiv;
#define glGetUniformuiv gGLFunc_glGetUniformuiv
extern PFNGLBINDFRAGDATALOCATIONPROC                    gGLFunc_glBindFragDataLocation;
#define glBindFragDataLocation gGLFunc_glBindFragDataLocation
extern PFNGLGETFRAGDATALOCATIONPROC                     gGLFunc_glGetFragDataLocation;
#define glGetFragDataLocation gGLFunc_glGetFragDataLocation
extern PFNGLUNIFORM1UIPROC                              gGLFunc_glUniform1ui;
#define glUniform1ui gGLFunc_glUniform1ui
extern PFNGLUNIFORM2UIPROC                              gGLFunc_glUniform2ui;
#define glUniform2ui gGLFunc_glUniform2ui
extern PFNGLUNIFORM3UIPROC                              gGLFunc_glUniform3ui;
#define glUniform3ui gGLFunc_glUniform3ui
extern PFNGLUNIFORM4UIPROC                              gGLFunc_glUniform4ui;
#define glUniform4ui gGLFunc_glUniform4ui
extern PFNGLUNIFORM1UIVPROC                             gGLFunc_glUniform1uiv;
#define glUniform1uiv gGLFunc_glUniform1uiv
extern PFNGLUNIFORM2UIVPROC                             gGLFunc_glUniform2uiv;
#define glUniform2uiv gGLFunc_glUniform2uiv
extern PFNGLUNIFORM3UIVPROC                             gGLFunc_glUniform3uiv;
#define glUniform3uiv gGLFunc_glUniform3uiv
extern PFNGLUNIFORM4UIVPROC                             gGLFunc_glUniform4uiv;
#define glUniform4uiv gGLFunc_glUniform4uiv
extern PFNGLTEXPARAMETERIIVPROC                         gGLFunc_glTexParameterIiv;
#define glTexParameterIiv gGLFunc_glTexParameterIiv
extern PFNGLTEXPARAMETERIUIVPROC                        gGLFunc_glTexParameterIuiv;
#define glTexParameterIuiv gGLFunc_glTexParameterIuiv
extern PFNGLGETTEXPARAMETERIIVPROC                      gGLFunc_glGetTexParameterIiv;
#define glGetTexParameterIiv gGLFunc_glGetTexParameterIiv
extern PFNGLGETTEXPARAMETERIUIVPROC                     gGLFunc_glGetTexParameterIuiv;
#define glGetTexParameterIuiv gGLFunc_glGetTexParameterIuiv
extern PFNGLCLEARBUFFERIVPROC                           gGLFunc_glClearBufferiv;
#define glClearBufferiv gGLFunc_glClearBufferiv
extern PFNGLCLEARBUFFERUIVPROC                          gGLFunc_glClearBufferuiv;
#define glClearBufferuiv gGLFunc_glClearBufferuiv
extern PFNGLCLEARBUFFERFVPROC                           gGLFunc_glClearBufferfv;
#define glClearBufferfv gGLFunc_glClearBufferfv
extern PFNGLCLEARBUFFERFIPROC                           gGLFunc_glClearBufferfi;
#define glClearBufferfi gGLFunc_glClearBufferfi
extern PFNGLGETSTRINGIPROC                              gGLFunc_glGetStringi;
#define glGetStringi gGLFunc_glGetStringi
extern PFNGLISRENDERBUFFERPROC                          gGLFunc_glIsRenderbuffer;
#define glIsRenderbuffer gGLFunc_glIsRenderbuffer
extern PFNGLBINDRENDERBUFFERPROC                        gGLFunc_glBindRenderbuffer;
#define glBindRenderbuffer gGLFunc_glBindRenderbuffer
extern PFNGLDELETERENDERBUFFERSPROC                     gGLFunc_glDeleteRenderbuffers;
#define glDeleteRenderbuffers gGLFunc_glDeleteRenderbuffers
extern PFNGLGENRENDERBUFFERSPROC                        gGLFunc_glGenRenderbuffers;
#define glGenRenderbuffers gGLFunc_glGenRenderbuffers
extern PFNGLRENDERBUFFERSTORAGEPROC                     gGLFunc_glRenderbufferStorage;
#define glRenderbufferStorage gGLFunc_glRenderbufferStorage
extern PFNGLGETRENDERBUFFERPARAMETERIVPROC              gGLFunc_glGetRenderbufferParameteriv;
#define glGetRenderbufferParameteriv gGLFunc_glGetRenderbufferParameteriv
extern PFNGLISFRAMEBUFFERPROC                           gGLFunc_glIsFramebuffer;
#define glIsFramebuffer gGLFunc_glIsFramebuffer
extern PFNGLBINDFRAMEBUFFERPROC                         gGLFunc_glBindFramebuffer;
#define glBindFramebuffer gGLFunc_glBindFramebuffer
extern PFNGLDELETEFRAMEBUFFERSPROC                      gGLFunc_glDeleteFramebuffers;
#define glDeleteFramebuffers gGLFunc_glDeleteFramebuffers
extern PFNGLGENFRAMEBUFFERSPROC                         gGLFunc_glGenFramebuffers;
#define glGenFramebuffers gGLFunc_glGenFramebuffers
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC                  gGLFunc_glCheckFramebufferStatus;
#define glCheckFramebufferStatus gGLFunc_glCheckFramebufferStatus
extern PFNGLFRAMEBUFFERTEXTURE1DPROC                    gGLFunc_glFramebufferTexture1D;
#define glFramebufferTexture1D gGLFunc_glFramebufferTexture1D
extern PFNGLFRAMEBUFFERTEXTURE2DPROC                    gGLFunc_glFramebufferTexture2D;
#define glFramebufferTexture2D gGLFunc_glFramebufferTexture2D
extern PFNGLFRAMEBUFFERTEXTURE3DPROC                    gGLFunc_glFramebufferTexture3D;
#define glFramebufferTexture3D gGLFunc_glFramebufferTexture3D
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC                 gGLFunc_glFramebufferRenderbuffer;
#define glFramebufferRenderbuffer gGLFunc_glFramebufferRenderbuffer
extern PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC     gGLFunc_glGetFramebufferAttachmentParameteriv;
#define glGetFramebufferAttachmentParameteriv gGLFunc_glGetFramebufferAttachmentParameteriv
extern PFNGLGENERATEMIPMAPPROC                          gGLFunc_glGenerateMipmap;
#define glGenerateMipmap gGLFunc_glGenerateMipmap
extern PFNGLBLITFRAMEBUFFERPROC                         gGLFunc_glBlitFramebuffer;
#define glBlitFramebuffer gGLFunc_glBlitFramebuffer
extern PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC          gGLFunc_glRenderbufferStorageMultisample;
#define glRenderbufferStorageMultisample gGLFunc_glRenderbufferStorageMultisample
extern PFNGLFRAMEBUFFERTEXTURELAYERPROC                 gGLFunc_glFramebufferTextureLayer;
#define glFramebufferTextureLayer gGLFunc_glFramebufferTextureLayer
extern PFNGLMAPBUFFERRANGEPROC                          gGLFunc_glMapBufferRange;
#define glMapBufferRange gGLFunc_glMapBufferRange
extern PFNGLFLUSHMAPPEDBUFFERRANGEPROC                  gGLFunc_glFlushMappedBufferRange;
#define glFlushMappedBufferRange gGLFunc_glFlushMappedBufferRange
extern PFNGLBINDVERTEXARRAYPROC                         gGLFunc_glBindVertexArray;
#define glBindVertexArray gGLFunc_glBindVertexArray
extern PFNGLDELETEVERTEXARRAYSPROC                      gGLFunc_glDeleteVertexArrays;
#define glDeleteVertexArrays gGLFunc_glDeleteVertexArrays
extern PFNGLGENVERTEXARRAYSPROC                         gGLFunc_glGenVertexArrays;
#define glGenVertexArrays gGLFunc_glGenVertexArrays
extern PFNGLISVERTEXARRAYPROC                           gGLFunc_glIsVertexArray;
#define glIsVertexArray gGLFunc_glIsVertexArray

// GL_VERSION_3_1
extern PFNGLDRAWARRAYSINSTANCEDPROC         gGLFunc_glDrawArraysInstanced;
#define glDrawArraysInstanced gGLFunc_glDrawArraysInstanced
extern PFNGLDRAWELEMENTSINSTANCEDPROC       gGLFunc_glDrawElementsInstanced;
#define glDrawElementsInstanced gGLFunc_glDrawElementsInstanced
extern PFNGLTEXBUFFERPROC                   gGLFunc_glTexBuffer;
#define glTexBuffer gGLFunc_glTexBuffer
extern PFNGLPRIMITIVERESTARTINDEXPROC       gGLFunc_glPrimitiveRestartIndex;
#define glPrimitiveRestartIndex gGLFunc_glPrimitiveRestartIndex
extern PFNGLCOPYBUFFERSUBDATAPROC           gGLFunc_glCopyBufferSubData;
#define glCopyBufferSubData gGLFunc_glCopyBufferSubData
extern PFNGLGETUNIFORMINDICESPROC           gGLFunc_glGetUniformIndices;
#define glGetUniformIndices gGLFunc_glGetUniformIndices
extern PFNGLGETACTIVEUNIFORMSIVPROC         gGLFunc_glGetActiveUniformsiv;
#define glGetActiveUniformsiv gGLFunc_glGetActiveUniformsiv
extern PFNGLGETACTIVEUNIFORMNAMEPROC        gGLFunc_glGetActiveUniformName;
#define glGetActiveUniformName gGLFunc_glGetActiveUniformName
extern PFNGLGETUNIFORMBLOCKINDEXPROC        gGLFunc_glGetUniformBlockIndex;
#define glGetUniformBlockIndex gGLFunc_glGetUniformBlockIndex
extern PFNGLGETACTIVEUNIFORMBLOCKIVPROC     gGLFunc_glGetActiveUniformBlockiv;
#define glGetActiveUniformBlockiv gGLFunc_glGetActiveUniformBlockiv
extern PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC   gGLFunc_glGetActiveUniformBlockName;
#define glGetActiveUniformBlockName gGLFunc_glGetActiveUniformBlockName
extern PFNGLUNIFORMBLOCKBINDINGPROC         gGLFunc_glUniformBlockBinding;
#define glUniformBlockBinding gGLFunc_glUniformBlockBinding

// GL_VERSION_3_2
extern PFNGLDRAWELEMENTSBASEVERTEXPROC          gGLFunc_glDrawElementsBaseVertex;
#define glDrawElementsBaseVertex gGLFunc_glDrawElementsBaseVertex
extern PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC     gGLFunc_glDrawRangeElementsBaseVertex;
#define glDrawRangeElementsBaseVertex gGLFunc_glDrawRangeElementsBaseVertex
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC gGLFunc_glDrawElementsInstancedBaseVertex;
#define glDrawElementsInstancedBaseVertex gGLFunc_glDrawElementsInstancedBaseVertex
extern PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC     gGLFunc_glMultiDrawElementsBaseVertex;
#define glMultiDrawElementsBaseVertex gGLFunc_glMultiDrawElementsBaseVertex
extern PFNGLPROVOKINGVERTEXPROC                 gGLFunc_glProvokingVertex;
#define glProvokingVertex gGLFunc_glProvokingVertex
extern PFNGLFENCESYNCPROC                       gGLFunc_glFenceSync;
#define glFenceSync gGLFunc_glFenceSync
extern PFNGLISSYNCPROC                          gGLFunc_glIsSync;
#define glIsSync gGLFunc_glIsSync
extern PFNGLDELETESYNCPROC                      gGLFunc_glDeleteSync;
#define glDeleteSync gGLFunc_glDeleteSync
extern PFNGLCLIENTWAITSYNCPROC                  gGLFunc_glClientWaitSync;
#define glClientWaitSync gGLFunc_glClientWaitSync
extern PFNGLWAITSYNCPROC                        gGLFunc_glWaitSync;
#define glWaitSync gGLFunc_glWaitSync
extern PFNGLGETINTEGER64VPROC                   gGLFunc_glGetInteger64v;
#define glGetInteger64v gGLFunc_glGetInteger64v
extern PFNGLGETSYNCIVPROC                       gGLFunc_glGetSynciv;
#define glGetSynciv gGLFunc_glGetSynciv
extern PFNGLGETINTEGER64I_VPROC                 gGLFunc_glGetInteger64i_v;
#define glGetInteger64i_v gGLFunc_glGetInteger64i_v
extern PFNGLGETBUFFERPARAMETERI64VPROC          gGLFunc_glGetBufferParameteri64v;
#define glGetBufferParameteri64v gGLFunc_glGetBufferParameteri64v
extern PFNGLFRAMEBUFFERTEXTUREPROC              gGLFunc_glFramebufferTexture;
#define glFramebufferTexture gGLFunc_glFramebufferTexture
extern PFNGLTEXIMAGE2DMULTISAMPLEPROC           gGLFunc_glTexImage2DMultisample;
#define glTexImage2DMultisample gGLFunc_glTexImage2DMultisample
extern PFNGLTEXIMAGE3DMULTISAMPLEPROC           gGLFunc_glTexImage3DMultisample;
#define glTexImage3DMultisample gGLFunc_glTexImage3DMultisample
extern PFNGLGETMULTISAMPLEFVPROC                gGLFunc_glGetMultisamplefv;
#define glGetMultisamplefv gGLFunc_glGetMultisamplefv
extern PFNGLSAMPLEMASKIPROC                     gGLFunc_glSampleMaski;
#define glSampleMaski gGLFunc_glSampleMaski

// GL_VERSION_3_3
extern PFNGLBINDFRAGDATALOCATIONINDEXEDPROC  gGLFunc_glBindFragDataLocationIndexed;
#define glBindFragDataLocationIndexed gGLFunc_glBindFragDataLocationIndexed
extern PFNGLGETFRAGDATAINDEXPROC             gGLFunc_glGetFragDataIndex;
#define glGetFragDataIndex gGLFunc_glGetFragDataIndex
extern PFNGLGENSAMPLERSPROC                  gGLFunc_glGenSamplers;
#define glGenSamplers gGLFunc_glGenSamplers
extern PFNGLDELETESAMPLERSPROC               gGLFunc_glDeleteSamplers;
#define glDeleteSamplers gGLFunc_glDeleteSamplers
extern PFNGLISSAMPLERPROC                    gGLFunc_glIsSampler;
#define glIsSampler gGLFunc_glIsSampler
extern PFNGLBINDSAMPLERPROC                  gGLFunc_glBindSampler;
#define glBindSampler gGLFunc_glBindSampler
extern PFNGLSAMPLERPARAMETERIPROC            gGLFunc_glSamplerParameteri;
#define glSamplerParameteri gGLFunc_glSamplerParameteri
extern PFNGLSAMPLERPARAMETERIVPROC           gGLFunc_glSamplerParameteriv;
#define glSamplerParameteriv gGLFunc_glSamplerParameteriv
extern PFNGLSAMPLERPARAMETERFPROC            gGLFunc_glSamplerParameterf;
#define glSamplerParameterf gGLFunc_glSamplerParameterf
extern PFNGLSAMPLERPARAMETERFVPROC           gGLFunc_glSamplerParameterfv;
#define glSamplerParameterfv gGLFunc_glSamplerParameterfv
extern PFNGLSAMPLERPARAMETERIIVPROC          gGLFunc_glSamplerParameterIiv;
#define glSamplerParameterIiv gGLFunc_glSamplerParameterIiv
extern PFNGLSAMPLERPARAMETERIUIVPROC         gGLFunc_glSamplerParameterIuiv;
#define glSamplerParameterIuiv gGLFunc_glSamplerParameterIuiv
extern PFNGLGETSAMPLERPARAMETERIVPROC        gGLFunc_glGetSamplerParameteriv;
#define glGetSamplerParameteriv gGLFunc_glGetSamplerParameteriv
extern PFNGLGETSAMPLERPARAMETERIIVPROC       gGLFunc_glGetSamplerParameterIiv;
#define glGetSamplerParameterIiv gGLFunc_glGetSamplerParameterIiv
extern PFNGLGETSAMPLERPARAMETERFVPROC        gGLFunc_glGetSamplerParameterfv;
#define glGetSamplerParameterfv gGLFunc_glGetSamplerParameterfv
extern PFNGLGETSAMPLERPARAMETERIUIVPROC      gGLFunc_glGetSamplerParameterIuiv;
#define glGetSamplerParameterIuiv gGLFunc_glGetSamplerParameterIuiv
extern PFNGLQUERYCOUNTERPROC                 gGLFunc_glQueryCounter;
#define glQueryCounter gGLFunc_glQueryCounter
extern PFNGLGETQUERYOBJECTI64VPROC           gGLFunc_glGetQueryObjecti64v;
#define glGetQueryObjecti64v gGLFunc_glGetQueryObjecti64v
extern PFNGLGETQUERYOBJECTUI64VPROC          gGLFunc_glGetQueryObjectui64v;
#define glGetQueryObjectui64v gGLFunc_glGetQueryObjectui64v
extern PFNGLVERTEXATTRIBDIVISORPROC          gGLFunc_glVertexAttribDivisor;
#define glVertexAttribDivisor gGLFunc_glVertexAttribDivisor
extern PFNGLVERTEXATTRIBP1UIPROC             gGLFunc_glVertexAttribP1ui;
#define glVertexAttribP1ui gGLFunc_glVertexAttribP1ui
extern PFNGLVERTEXATTRIBP1UIVPROC            gGLFunc_glVertexAttribP1uiv;
#define glVertexAttribP1uiv gGLFunc_glVertexAttribP1uiv
extern PFNGLVERTEXATTRIBP2UIPROC             gGLFunc_glVertexAttribP2ui;
#define glVertexAttribP2ui gGLFunc_glVertexAttribP2ui
extern PFNGLVERTEXATTRIBP2UIVPROC            gGLFunc_glVertexAttribP2uiv;
#define glVertexAttribP2uiv gGLFunc_glVertexAttribP2uiv
extern PFNGLVERTEXATTRIBP3UIPROC             gGLFunc_glVertexAttribP3ui;
#define glVertexAttribP3ui gGLFunc_glVertexAttribP3ui
extern PFNGLVERTEXATTRIBP3UIVPROC            gGLFunc_glVertexAttribP3uiv;
#define glVertexAttribP3uiv gGLFunc_glVertexAttribP3uiv
extern PFNGLVERTEXATTRIBP4UIPROC             gGLFunc_glVertexAttribP4ui;
#define glVertexAttribP4ui gGLFunc_glVertexAttribP4ui
extern PFNGLVERTEXATTRIBP4UIVPROC            gGLFunc_glVertexAttribP4uiv;
#define glVertexAttribP4uiv gGLFunc_glVertexAttribP4uiv
extern PFNGLVERTEXP2UIPROC                   gGLFunc_glVertexP2ui;
#define glVertexP2ui gGLFunc_glVertexP2ui
extern PFNGLVERTEXP2UIVPROC                  gGLFunc_glVertexP2uiv;
#define glVertexP2uiv gGLFunc_glVertexP2uiv
extern PFNGLVERTEXP3UIPROC                   gGLFunc_glVertexP3ui;
#define glVertexP3ui gGLFunc_glVertexP3ui
extern PFNGLVERTEXP3UIVPROC                  gGLFunc_glVertexP3uiv;
#define glVertexP3uiv gGLFunc_glVertexP3uiv
extern PFNGLVERTEXP4UIPROC                   gGLFunc_glVertexP4ui;
#define glVertexP4ui gGLFunc_glVertexP4ui
extern PFNGLVERTEXP4UIVPROC                  gGLFunc_glVertexP4uiv;
#define glVertexP4uiv gGLFunc_glVertexP4uiv
extern PFNGLTEXCOORDP1UIPROC                 gGLFunc_glTexCoordP1ui;
#define glTexCoordP1ui gGLFunc_glTexCoordP1ui
extern PFNGLTEXCOORDP1UIVPROC                gGLFunc_glTexCoordP1uiv;
#define glTexCoordP1uiv gGLFunc_glTexCoordP1uiv
extern PFNGLTEXCOORDP2UIPROC                 gGLFunc_glTexCoordP2ui;
#define glTexCoordP2ui gGLFunc_glTexCoordP2ui
extern PFNGLTEXCOORDP2UIVPROC                gGLFunc_glTexCoordP2uiv;
#define glTexCoordP2uiv gGLFunc_glTexCoordP2uiv
extern PFNGLTEXCOORDP3UIPROC                 gGLFunc_glTexCoordP3ui;
#define glTexCoordP3ui gGLFunc_glTexCoordP3ui
extern PFNGLTEXCOORDP3UIVPROC                gGLFunc_glTexCoordP3uiv;
#define glTexCoordP3uiv gGLFunc_glTexCoordP3uiv
extern PFNGLTEXCOORDP4UIPROC                 gGLFunc_glTexCoordP4ui;
#define glTexCoordP4ui gGLFunc_glTexCoordP4ui
extern PFNGLTEXCOORDP4UIVPROC                gGLFunc_glTexCoordP4uiv;
#define glTexCoordP4uiv gGLFunc_glTexCoordP4uiv
extern PFNGLMULTITEXCOORDP1UIPROC            gGLFunc_glMultiTexCoordP1ui;
#define glMultiTexCoordP1ui gGLFunc_glMultiTexCoordP1ui
extern PFNGLMULTITEXCOORDP1UIVPROC           gGLFunc_glMultiTexCoordP1uiv;
#define glMultiTexCoordP1uiv gGLFunc_glMultiTexCoordP1uiv
extern PFNGLMULTITEXCOORDP2UIPROC            gGLFunc_glMultiTexCoordP2ui;
#define glMultiTexCoordP2ui gGLFunc_glMultiTexCoordP2ui
extern PFNGLMULTITEXCOORDP2UIVPROC           gGLFunc_glMultiTexCoordP2uiv;
#define glMultiTexCoordP2uiv gGLFunc_glMultiTexCoordP2uiv
extern PFNGLMULTITEXCOORDP3UIPROC            gGLFunc_glMultiTexCoordP3ui;
#define glMultiTexCoordP3ui gGLFunc_glMultiTexCoordP3ui
extern PFNGLMULTITEXCOORDP3UIVPROC           gGLFunc_glMultiTexCoordP3uiv;
#define glMultiTexCoordP3uiv gGLFunc_glMultiTexCoordP3uiv
extern PFNGLMULTITEXCOORDP4UIPROC            gGLFunc_glMultiTexCoordP4ui;
#define glMultiTexCoordP4ui gGLFunc_glMultiTexCoordP4ui
extern PFNGLMULTITEXCOORDP4UIVPROC           gGLFunc_glMultiTexCoordP4uiv;
#define glMultiTexCoordP4uiv gGLFunc_glMultiTexCoordP4uiv
extern PFNGLNORMALP3UIPROC                   gGLFunc_glNormalP3ui;
#define glNormalP3ui gGLFunc_glNormalP3ui
extern PFNGLNORMALP3UIVPROC                  gGLFunc_glNormalP3uiv;
#define glNormalP3uiv gGLFunc_glNormalP3uiv
extern PFNGLCOLORP3UIPROC                    gGLFunc_glColorP3ui;
#define glColorP3ui gGLFunc_glColorP3ui
extern PFNGLCOLORP3UIVPROC                   gGLFunc_glColorP3uiv;
#define glColorP3uiv gGLFunc_glColorP3uiv
extern PFNGLCOLORP4UIPROC                    gGLFunc_glColorP4ui;
#define glColorP4ui gGLFunc_glColorP4ui
extern PFNGLCOLORP4UIVPROC                   gGLFunc_glColorP4uiv;
#define glColorP4uiv gGLFunc_glColorP4uiv
extern PFNGLSECONDARYCOLORP3UIPROC           gGLFunc_glSecondaryColorP3ui;
#define glSecondaryColorP3ui gGLFunc_glSecondaryColorP3ui
extern PFNGLSECONDARYCOLORP3UIVPROC          gGLFunc_glSecondaryColorP3uiv;
#define glSecondaryColorP3uiv gGLFunc_glSecondaryColorP3uiv

// GL_VERSION_4_0
extern PFNGLMINSAMPLESHADINGPROC                gGLFunc_glMinSampleShading;
#define glMinSampleShading gGLFunc_glMinSampleShading
extern PFNGLBLENDEQUATIONIPROC                  gGLFunc_glBlendEquationi;
#define glBlendEquationi gGLFunc_glBlendEquationi
extern PFNGLBLENDEQUATIONSEPARATEIPROC          gGLFunc_glBlendEquationSeparatei;
#define glBlendEquationSeparatei gGLFunc_glBlendEquationSeparatei
extern PFNGLBLENDFUNCIPROC                      gGLFunc_glBlendFunci;
#define glBlendFunci gGLFunc_glBlendFunci
extern PFNGLBLENDFUNCSEPARATEIPROC              gGLFunc_glBlendFuncSeparatei;
#define glBlendFuncSeparatei gGLFunc_glBlendFuncSeparatei
extern PFNGLDRAWARRAYSINDIRECTPROC              gGLFunc_glDrawArraysIndirect;
#define glDrawArraysIndirect gGLFunc_glDrawArraysIndirect
extern PFNGLDRAWELEMENTSINDIRECTPROC            gGLFunc_glDrawElementsIndirect;
#define glDrawElementsIndirect gGLFunc_glDrawElementsIndirect
extern PFNGLUNIFORM1DPROC                       gGLFunc_glUniform1d;
#define glUniform1d gGLFunc_glUniform1d
extern PFNGLUNIFORM2DPROC                       gGLFunc_glUniform2d;
#define glUniform2d gGLFunc_glUniform2d
extern PFNGLUNIFORM3DPROC                       gGLFunc_glUniform3d;
#define glUniform3d gGLFunc_glUniform3d
extern PFNGLUNIFORM4DPROC                       gGLFunc_glUniform4d;
#define glUniform4d gGLFunc_glUniform4d
extern PFNGLUNIFORM1DVPROC                      gGLFunc_glUniform1dv;
#define glUniform1dv gGLFunc_glUniform1dv
extern PFNGLUNIFORM2DVPROC                      gGLFunc_glUniform2dv;
#define glUniform2dv gGLFunc_glUniform2dv
extern PFNGLUNIFORM3DVPROC                      gGLFunc_glUniform3dv;
#define glUniform3dv gGLFunc_glUniform3dv
extern PFNGLUNIFORM4DVPROC                      gGLFunc_glUniform4dv;
#define glUniform4dv gGLFunc_glUniform4dv
extern PFNGLUNIFORMMATRIX2DVPROC                gGLFunc_glUniformMatrix2dv;
#define glUniformMatrix2dv gGLFunc_glUniformMatrix2dv
extern PFNGLUNIFORMMATRIX3DVPROC                gGLFunc_glUniformMatrix3dv;
#define glUniformMatrix3dv gGLFunc_glUniformMatrix3dv
extern PFNGLUNIFORMMATRIX4DVPROC                gGLFunc_glUniformMatrix4dv;
#define glUniformMatrix4dv gGLFunc_glUniformMatrix4dv
extern PFNGLUNIFORMMATRIX2X3DVPROC              gGLFunc_glUniformMatrix2x3dv;
#define glUniformMatrix2x3dv gGLFunc_glUniformMatrix2x3dv
extern PFNGLUNIFORMMATRIX2X4DVPROC              gGLFunc_glUniformMatrix2x4dv;
#define glUniformMatrix2x4dv gGLFunc_glUniformMatrix2x4dv
extern PFNGLUNIFORMMATRIX3X2DVPROC              gGLFunc_glUniformMatrix3x2dv;
#define glUniformMatrix3x2dv gGLFunc_glUniformMatrix3x2dv
extern PFNGLUNIFORMMATRIX3X4DVPROC              gGLFunc_glUniformMatrix3x4dv;
#define glUniformMatrix3x4dv gGLFunc_glUniformMatrix3x4dv
extern PFNGLUNIFORMMATRIX4X2DVPROC              gGLFunc_glUniformMatrix4x2dv;
#define glUniformMatrix4x2dv gGLFunc_glUniformMatrix4x2dv
extern PFNGLUNIFORMMATRIX4X3DVPROC              gGLFunc_glUniformMatrix4x3dv;
#define glUniformMatrix4x3dv gGLFunc_glUniformMatrix4x3dv
extern PFNGLGETUNIFORMDVPROC                    gGLFunc_glGetUniformdv;
#define glGetUniformdv gGLFunc_glGetUniformdv
extern PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC    gGLFunc_glGetSubroutineUniformLocation;
#define glGetSubroutineUniformLocation gGLFunc_glGetSubroutineUniformLocation
extern PFNGLGETSUBROUTINEINDEXPROC              gGLFunc_glGetSubroutineIndex;
#define glGetSubroutineIndex gGLFunc_glGetSubroutineIndex
extern PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC    gGLFunc_glGetActiveSubroutineUniformiv;
#define glGetActiveSubroutineUniformiv gGLFunc_glGetActiveSubroutineUniformiv
extern PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC  gGLFunc_glGetActiveSubroutineUniformName;
#define glGetActiveSubroutineUniformName gGLFunc_glGetActiveSubroutineUniformName
extern PFNGLGETACTIVESUBROUTINENAMEPROC         gGLFunc_glGetActiveSubroutineName;
#define glGetActiveSubroutineName gGLFunc_glGetActiveSubroutineName
extern PFNGLUNIFORMSUBROUTINESUIVPROC           gGLFunc_glUniformSubroutinesuiv;
#define glUniformSubroutinesuiv gGLFunc_glUniformSubroutinesuiv
extern PFNGLGETUNIFORMSUBROUTINEUIVPROC         gGLFunc_glGetUniformSubroutineuiv;
#define glGetUniformSubroutineuiv gGLFunc_glGetUniformSubroutineuiv
extern PFNGLGETPROGRAMSTAGEIVPROC               gGLFunc_glGetProgramStageiv;
#define glGetProgramStageiv gGLFunc_glGetProgramStageiv
extern PFNGLPATCHPARAMETERIPROC                 gGLFunc_glPatchParameteri;
#define glPatchParameteri gGLFunc_glPatchParameteri
extern PFNGLPATCHPARAMETERFVPROC                gGLFunc_glPatchParameterfv;
#define glPatchParameterfv gGLFunc_glPatchParameterfv
extern PFNGLBINDTRANSFORMFEEDBACKPROC           gGLFunc_glBindTransformFeedback;
#define glBindTransformFeedback gGLFunc_glBindTransformFeedback
extern PFNGLDELETETRANSFORMFEEDBACKSPROC        gGLFunc_glDeleteTransformFeedbacks;
#define glDeleteTransformFeedbacks gGLFunc_glDeleteTransformFeedbacks
extern PFNGLGENTRANSFORMFEEDBACKSPROC           gGLFunc_glGenTransformFeedbacks;
#define glGenTransformFeedbacks gGLFunc_glGenTransformFeedbacks
extern PFNGLISTRANSFORMFEEDBACKPROC             gGLFunc_glIsTransformFeedback;
#define glIsTransformFeedback gGLFunc_glIsTransformFeedback
extern PFNGLPAUSETRANSFORMFEEDBACKPROC          gGLFunc_glPauseTransformFeedback;
#define glPauseTransformFeedback gGLFunc_glPauseTransformFeedback
extern PFNGLRESUMETRANSFORMFEEDBACKPROC         gGLFunc_glResumeTransformFeedback;
#define glResumeTransformFeedback gGLFunc_glResumeTransformFeedback
extern PFNGLDRAWTRANSFORMFEEDBACKPROC           gGLFunc_glDrawTransformFeedback;
#define glDrawTransformFeedback gGLFunc_glDrawTransformFeedback
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC     gGLFunc_glDrawTransformFeedbackStream;
#define glDrawTransformFeedbackStream gGLFunc_glDrawTransformFeedbackStream
extern PFNGLBEGINQUERYINDEXEDPROC               gGLFunc_glBeginQueryIndexed;
#define glBeginQueryIndexed gGLFunc_glBeginQueryIndexed
extern PFNGLENDQUERYINDEXEDPROC                 gGLFunc_glEndQueryIndexed;
#define glEndQueryIndexed gGLFunc_glEndQueryIndexed
extern PFNGLGETQUERYINDEXEDIVPROC               gGLFunc_glGetQueryIndexediv;
#define glGetQueryIndexediv gGLFunc_glGetQueryIndexediv

 // GL_VERSION_4_1
extern PFNGLRELEASESHADERCOMPILERPROC           gGLFunc_glReleaseShaderCompiler;
#define glReleaseShaderCompiler gGLFunc_glReleaseShaderCompiler
extern PFNGLSHADERBINARYPROC                    gGLFunc_glShaderBinary;
#define glShaderBinary gGLFunc_glShaderBinary
extern PFNGLGETSHADERPRECISIONFORMATPROC        gGLFunc_glGetShaderPrecisionFormat;
#define glGetShaderPrecisionFormat gGLFunc_glGetShaderPrecisionFormat
extern PFNGLDEPTHRANGEFPROC                     gGLFunc_glDepthRangef;
#define glDepthRangef gGLFunc_glDepthRangef
extern PFNGLCLEARDEPTHFPROC                     gGLFunc_glClearDepthf;
#define glClearDepthf gGLFunc_glClearDepthf
extern PFNGLGETPROGRAMBINARYPROC                gGLFunc_glGetProgramBinary;
#define glGetProgramBinary gGLFunc_glGetProgramBinary
extern PFNGLPROGRAMBINARYPROC                   gGLFunc_glProgramBinary;
#define glProgramBinary gGLFunc_glProgramBinary
extern PFNGLPROGRAMPARAMETERIPROC               gGLFunc_glProgramParameteri;
#define glProgramParameteri gGLFunc_glProgramParameteri
extern PFNGLUSEPROGRAMSTAGESPROC                gGLFunc_glUseProgramStages;
#define glUseProgramStages gGLFunc_glUseProgramStages
extern PFNGLACTIVESHADERPROGRAMPROC             gGLFunc_glActiveShaderProgram;
#define glActiveShaderProgram gGLFunc_glActiveShaderProgram
extern PFNGLCREATESHADERPROGRAMVPROC            gGLFunc_glCreateShaderProgramv;
#define glCreateShaderProgramv gGLFunc_glCreateShaderProgramv
extern PFNGLBINDPROGRAMPIPELINEPROC             gGLFunc_glBindProgramPipeline;
#define glBindProgramPipeline gGLFunc_glBindProgramPipeline
extern PFNGLDELETEPROGRAMPIPELINESPROC          gGLFunc_glDeleteProgramPipelines;
#define glDeleteProgramPipelines gGLFunc_glDeleteProgramPipelines
extern PFNGLGENPROGRAMPIPELINESPROC             gGLFunc_glGenProgramPipelines;
#define glGenProgramPipelines gGLFunc_glGenProgramPipelines
extern PFNGLISPROGRAMPIPELINEPROC               gGLFunc_glIsProgramPipeline;
#define glIsProgramPipeline gGLFunc_glIsProgramPipeline
extern PFNGLGETPROGRAMPIPELINEIVPROC            gGLFunc_glGetProgramPipelineiv;
#define glGetProgramPipelineiv gGLFunc_glGetProgramPipelineiv
extern PFNGLPROGRAMUNIFORM1IPROC                gGLFunc_glProgramUniform1i;
#define glProgramUniform1i gGLFunc_glProgramUniform1i
extern PFNGLPROGRAMUNIFORM1IVPROC               gGLFunc_glProgramUniform1iv;
#define glProgramUniform1iv gGLFunc_glProgramUniform1iv
extern PFNGLPROGRAMUNIFORM1FPROC                gGLFunc_glProgramUniform1f;
#define glProgramUniform1f gGLFunc_glProgramUniform1f
extern PFNGLPROGRAMUNIFORM1FVPROC               gGLFunc_glProgramUniform1fv;
#define glProgramUniform1fv gGLFunc_glProgramUniform1fv
extern PFNGLPROGRAMUNIFORM1DPROC                gGLFunc_glProgramUniform1d;
#define glProgramUniform1d gGLFunc_glProgramUniform1d
extern PFNGLPROGRAMUNIFORM1DVPROC               gGLFunc_glProgramUniform1dv;
#define glProgramUniform1dv gGLFunc_glProgramUniform1dv
extern PFNGLPROGRAMUNIFORM1UIPROC               gGLFunc_glProgramUniform1ui;
#define glProgramUniform1ui gGLFunc_glProgramUniform1ui
extern PFNGLPROGRAMUNIFORM1UIVPROC              gGLFunc_glProgramUniform1uiv;
#define glProgramUniform1uiv gGLFunc_glProgramUniform1uiv
extern PFNGLPROGRAMUNIFORM2IPROC                gGLFunc_glProgramUniform2i;
#define glProgramUniform2i gGLFunc_glProgramUniform2i
extern PFNGLPROGRAMUNIFORM2IVPROC               gGLFunc_glProgramUniform2iv;
#define glProgramUniform2iv gGLFunc_glProgramUniform2iv
extern PFNGLPROGRAMUNIFORM2FPROC                gGLFunc_glProgramUniform2f;
#define glProgramUniform2f gGLFunc_glProgramUniform2f
extern PFNGLPROGRAMUNIFORM2FVPROC               gGLFunc_glProgramUniform2fv;
#define glProgramUniform2fv gGLFunc_glProgramUniform2fv
extern PFNGLPROGRAMUNIFORM2DPROC                gGLFunc_glProgramUniform2d;
#define glProgramUniform2d gGLFunc_glProgramUniform2d
extern PFNGLPROGRAMUNIFORM2DVPROC               gGLFunc_glProgramUniform2dv;
#define glProgramUniform2dv gGLFunc_glProgramUniform2dv
extern PFNGLPROGRAMUNIFORM2UIPROC               gGLFunc_glProgramUniform2ui;
#define glProgramUniform2ui gGLFunc_glProgramUniform2ui
extern PFNGLPROGRAMUNIFORM2UIVPROC              gGLFunc_glProgramUniform2uiv;
#define glProgramUniform2uiv gGLFunc_glProgramUniform2uiv
extern PFNGLPROGRAMUNIFORM3IPROC                gGLFunc_glProgramUniform3i;
#define glProgramUniform3i gGLFunc_glProgramUniform3i
extern PFNGLPROGRAMUNIFORM3IVPROC               gGLFunc_glProgramUniform3iv;
#define glProgramUniform3iv gGLFunc_glProgramUniform3iv
extern PFNGLPROGRAMUNIFORM3FPROC                gGLFunc_glProgramUniform3f;
#define glProgramUniform3f gGLFunc_glProgramUniform3f
extern PFNGLPROGRAMUNIFORM3FVPROC               gGLFunc_glProgramUniform3fv;
#define glProgramUniform3fv gGLFunc_glProgramUniform3fv
extern PFNGLPROGRAMUNIFORM3DPROC                gGLFunc_glProgramUniform3d;
#define glProgramUniform3d gGLFunc_glProgramUniform3d
extern PFNGLPROGRAMUNIFORM3DVPROC               gGLFunc_glProgramUniform3dv;
#define glProgramUniform3dv gGLFunc_glProgramUniform3dv
extern PFNGLPROGRAMUNIFORM3UIPROC               gGLFunc_glProgramUniform3ui;
#define glProgramUniform3ui gGLFunc_glProgramUniform3ui
extern PFNGLPROGRAMUNIFORM3UIVPROC              gGLFunc_glProgramUniform3uiv;
#define glProgramUniform3uiv gGLFunc_glProgramUniform3uiv
extern PFNGLPROGRAMUNIFORM4IPROC                gGLFunc_glProgramUniform4i;
#define glProgramUniform4i gGLFunc_glProgramUniform4i
extern PFNGLPROGRAMUNIFORM4IVPROC               gGLFunc_glProgramUniform4iv;
#define glProgramUniform4iv gGLFunc_glProgramUniform4iv
extern PFNGLPROGRAMUNIFORM4FPROC                gGLFunc_glProgramUniform4f;
#define glProgramUniform4f gGLFunc_glProgramUniform4f
extern PFNGLPROGRAMUNIFORM4FVPROC               gGLFunc_glProgramUniform4fv;
#define glProgramUniform4fv gGLFunc_glProgramUniform4fv
extern PFNGLPROGRAMUNIFORM4DPROC                gGLFunc_glProgramUniform4d;
#define glProgramUniform4d gGLFunc_glProgramUniform4d
extern PFNGLPROGRAMUNIFORM4DVPROC               gGLFunc_glProgramUniform4dv;
#define glProgramUniform4dv gGLFunc_glProgramUniform4dv
extern PFNGLPROGRAMUNIFORM4UIPROC               gGLFunc_glProgramUniform4ui;
#define glProgramUniform4ui gGLFunc_glProgramUniform4ui
extern PFNGLPROGRAMUNIFORM4UIVPROC              gGLFunc_glProgramUniform4uiv;
#define glProgramUniform4uiv gGLFunc_glProgramUniform4uiv
extern PFNGLPROGRAMUNIFORMMATRIX2FVPROC         gGLFunc_glProgramUniformMatrix2fv;
#define glProgramUniformMatrix2fv gGLFunc_glProgramUniformMatrix2fv
extern PFNGLPROGRAMUNIFORMMATRIX3FVPROC         gGLFunc_glProgramUniformMatrix3fv;
#define glProgramUniformMatrix3fv gGLFunc_glProgramUniformMatrix3fv
extern PFNGLPROGRAMUNIFORMMATRIX4FVPROC         gGLFunc_glProgramUniformMatrix4fv;
#define glProgramUniformMatrix4fv gGLFunc_glProgramUniformMatrix4fv
extern PFNGLPROGRAMUNIFORMMATRIX2DVPROC         gGLFunc_glProgramUniformMatrix2dv;
#define glProgramUniformMatrix2dv gGLFunc_glProgramUniformMatrix2dv
extern PFNGLPROGRAMUNIFORMMATRIX3DVPROC         gGLFunc_glProgramUniformMatrix3dv;
#define glProgramUniformMatrix3dv gGLFunc_glProgramUniformMatrix3dv
extern PFNGLPROGRAMUNIFORMMATRIX4DVPROC         gGLFunc_glProgramUniformMatrix4dv;
#define glProgramUniformMatrix4dv gGLFunc_glProgramUniformMatrix4dv
extern PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC       gGLFunc_glProgramUniformMatrix2x3fv;
#define glProgramUniformMatrix2x3fv gGLFunc_glProgramUniformMatrix2x3fv
extern PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC       gGLFunc_glProgramUniformMatrix3x2fv;
#define glProgramUniformMatrix3x2fv gGLFunc_glProgramUniformMatrix3x2fv
extern PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC       gGLFunc_glProgramUniformMatrix2x4fv;
#define glProgramUniformMatrix2x4fv gGLFunc_glProgramUniformMatrix2x4fv
extern PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC       gGLFunc_glProgramUniformMatrix4x2fv;
#define glProgramUniformMatrix4x2fv gGLFunc_glProgramUniformMatrix4x2fv
extern PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC       gGLFunc_glProgramUniformMatrix3x4fv;
#define glProgramUniformMatrix3x4fv gGLFunc_glProgramUniformMatrix3x4fv
extern PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC       gGLFunc_glProgramUniformMatrix4x3fv;
#define glProgramUniformMatrix4x3fv gGLFunc_glProgramUniformMatrix4x3fv
extern PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC       gGLFunc_glProgramUniformMatrix2x3dv;
#define glProgramUniformMatrix2x3dv gGLFunc_glProgramUniformMatrix2x3dv
extern PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC       gGLFunc_glProgramUniformMatrix3x2dv;
#define glProgramUniformMatrix3x2dv gGLFunc_glProgramUniformMatrix3x2dv
extern PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC       gGLFunc_glProgramUniformMatrix2x4dv;
#define glProgramUniformMatrix2x4dv gGLFunc_glProgramUniformMatrix2x4dv
extern PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC       gGLFunc_glProgramUniformMatrix4x2dv;
#define glProgramUniformMatrix4x2dv gGLFunc_glProgramUniformMatrix4x2dv
extern PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC       gGLFunc_glProgramUniformMatrix3x4dv;
#define glProgramUniformMatrix3x4dv gGLFunc_glProgramUniformMatrix3x4dv
extern PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC       gGLFunc_glProgramUniformMatrix4x3dv;
#define glProgramUniformMatrix4x3dv gGLFunc_glProgramUniformMatrix4x3dv
extern PFNGLVALIDATEPROGRAMPIPELINEPROC         gGLFunc_glValidateProgramPipeline;
#define glValidateProgramPipeline gGLFunc_glValidateProgramPipeline
extern PFNGLGETPROGRAMPIPELINEINFOLOGPROC       gGLFunc_glGetProgramPipelineInfoLog;
#define glGetProgramPipelineInfoLog gGLFunc_glGetProgramPipelineInfoLog
extern PFNGLVERTEXATTRIBL1DPROC                 gGLFunc_glVertexAttribL1d;
#define glVertexAttribL1d gGLFunc_glVertexAttribL1d
extern PFNGLVERTEXATTRIBL2DPROC                 gGLFunc_glVertexAttribL2d;
#define glVertexAttribL2d gGLFunc_glVertexAttribL2d
extern PFNGLVERTEXATTRIBL3DPROC                 gGLFunc_glVertexAttribL3d;
#define glVertexAttribL3d gGLFunc_glVertexAttribL3d
extern PFNGLVERTEXATTRIBL4DPROC                 gGLFunc_glVertexAttribL4d;
#define glVertexAttribL4d gGLFunc_glVertexAttribL4d
extern PFNGLVERTEXATTRIBL1DVPROC                gGLFunc_glVertexAttribL1dv;
#define glVertexAttribL1dv gGLFunc_glVertexAttribL1dv
extern PFNGLVERTEXATTRIBL2DVPROC                gGLFunc_glVertexAttribL2dv;
#define glVertexAttribL2dv gGLFunc_glVertexAttribL2dv
extern PFNGLVERTEXATTRIBL3DVPROC                gGLFunc_glVertexAttribL3dv;
#define glVertexAttribL3dv gGLFunc_glVertexAttribL3dv
extern PFNGLVERTEXATTRIBL4DVPROC                gGLFunc_glVertexAttribL4dv;
#define glVertexAttribL4dv gGLFunc_glVertexAttribL4dv
extern PFNGLVERTEXATTRIBLPOINTERPROC            gGLFunc_glVertexAttribLPointer;
#define glVertexAttribLPointer gGLFunc_glVertexAttribLPointer
extern PFNGLGETVERTEXATTRIBLDVPROC              gGLFunc_glGetVertexAttribLdv;
#define glGetVertexAttribLdv gGLFunc_glGetVertexAttribLdv
extern PFNGLVIEWPORTARRAYVPROC                  gGLFunc_glViewportArrayv;
#define glViewportArrayv gGLFunc_glViewportArrayv
extern PFNGLVIEWPORTINDEXEDFPROC                gGLFunc_glViewportIndexedf;
#define glViewportIndexedf gGLFunc_glViewportIndexedf
extern PFNGLVIEWPORTINDEXEDFVPROC               gGLFunc_glViewportIndexedfv;
#define glViewportIndexedfv gGLFunc_glViewportIndexedfv
extern PFNGLSCISSORARRAYVPROC                   gGLFunc_glScissorArrayv;
#define glScissorArrayv gGLFunc_glScissorArrayv
extern PFNGLSCISSORINDEXEDPROC                  gGLFunc_glScissorIndexed;
#define glScissorIndexed gGLFunc_glScissorIndexed
extern PFNGLSCISSORINDEXEDVPROC                 gGLFunc_glScissorIndexedv;
#define glScissorIndexedv gGLFunc_glScissorIndexedv
extern PFNGLDEPTHRANGEARRAYVPROC                gGLFunc_glDepthRangeArrayv;
#define glDepthRangeArrayv gGLFunc_glDepthRangeArrayv
extern PFNGLDEPTHRANGEINDEXEDPROC               gGLFunc_glDepthRangeIndexed;
#define glDepthRangeIndexed gGLFunc_glDepthRangeIndexed
extern PFNGLGETFLOATI_VPROC                     gGLFunc_glGetFloati_v;
#define glGetFloati_v gGLFunc_glGetFloati_v
extern PFNGLGETDOUBLEI_VPROC                    gGLFunc_glGetDoublei_v;
#define glGetDoublei_v gGLFunc_glGetDoublei_v

// GL_VERSION_4_2
extern PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC             gGLFunc_glDrawArraysInstancedBaseInstance;
#define glDrawArraysInstancedBaseInstance gGLFunc_glDrawArraysInstancedBaseInstance
extern PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC           gGLFunc_glDrawElementsInstancedBaseInstance;
#define glDrawElementsInstancedBaseInstance gGLFunc_glDrawElementsInstancedBaseInstance
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC gGLFunc_glDrawElementsInstancedBaseVertexBaseInstance;
#define glDrawElementsInstancedBaseVertexBaseInstance gGLFunc_glDrawElementsInstancedBaseVertexBaseInstance
extern PFNGLGETINTERNALFORMATIVPROC                         gGLFunc_glGetInternalformativ;
#define glGetInternalformativ gGLFunc_glGetInternalformativ
extern PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC              gGLFunc_glGetActiveAtomicCounterBufferiv;
#define glGetActiveAtomicCounterBufferiv gGLFunc_glGetActiveAtomicCounterBufferiv
extern PFNGLBINDIMAGETEXTUREPROC                            gGLFunc_glBindImageTexture;
#define glBindImageTexture gGLFunc_glBindImageTexture
extern PFNGLMEMORYBARRIERPROC                               gGLFunc_glMemoryBarrier;
#define glMemoryBarrier gGLFunc_glMemoryBarrier
extern PFNGLTEXSTORAGE1DPROC                                gGLFunc_glTexStorage1D;
#define glTexStorage1D gGLFunc_glTexStorage1D
extern PFNGLTEXSTORAGE2DPROC                                gGLFunc_glTexStorage2D;
#define glTexStorage2D gGLFunc_glTexStorage2D
extern PFNGLTEXSTORAGE3DPROC                                gGLFunc_glTexStorage3D;
#define glTexStorage3D gGLFunc_glTexStorage3D
extern PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC              gGLFunc_glDrawTransformFeedbackInstanced;
#define glDrawTransformFeedbackInstanced gGLFunc_glDrawTransformFeedbackInstanced
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC        gGLFunc_glDrawTransformFeedbackStreamInstanced;
#define glDrawTransformFeedbackStreamInstanced gGLFunc_glDrawTransformFeedbackStreamInstanced

// GL_VERSION_4_3
extern PFNGLCLEARBUFFERDATAPROC                             gGLFunc_glClearBufferData;
#define glClearBufferData gGLFunc_glClearBufferData
extern PFNGLCLEARBUFFERSUBDATAPROC                          gGLFunc_glClearBufferSubData;
#define glClearBufferSubData gGLFunc_glClearBufferSubData
extern PFNGLDISPATCHCOMPUTEPROC                             gGLFunc_glDispatchCompute;
#define glDispatchCompute gGLFunc_glDispatchCompute
extern PFNGLDISPATCHCOMPUTEINDIRECTPROC                     gGLFunc_glDispatchComputeIndirect;
#define glDispatchComputeIndirect gGLFunc_glDispatchComputeIndirect
extern PFNGLCOPYIMAGESUBDATAPROC                            gGLFunc_glCopyImageSubData;
#define glCopyImageSubData gGLFunc_glCopyImageSubData
extern PFNGLFRAMEBUFFERPARAMETERIPROC                       gGLFunc_glFramebufferParameteri;
#define glFramebufferParameteri gGLFunc_glFramebufferParameteri
extern PFNGLGETFRAMEBUFFERPARAMETERIVPROC                   gGLFunc_glGetFramebufferParameteriv;
#define glGetFramebufferParameteriv gGLFunc_glGetFramebufferParameteriv
extern PFNGLGETINTERNALFORMATI64VPROC                       gGLFunc_glGetInternalformati64v;
#define glGetInternalformati64v gGLFunc_glGetInternalformati64v
extern PFNGLINVALIDATETEXSUBIMAGEPROC                       gGLFunc_glInvalidateTexSubImage;
#define glInvalidateTexSubImage gGLFunc_glInvalidateTexSubImage
extern PFNGLINVALIDATETEXIMAGEPROC                          gGLFunc_glInvalidateTexImage;
#define glInvalidateTexImage gGLFunc_glInvalidateTexImage
extern PFNGLINVALIDATEBUFFERSUBDATAPROC                     gGLFunc_glInvalidateBufferSubData;
#define glInvalidateBufferSubData gGLFunc_glInvalidateBufferSubData
extern PFNGLINVALIDATEBUFFERDATAPROC                        gGLFunc_glInvalidateBufferData;
#define glInvalidateBufferData gGLFunc_glInvalidateBufferData
extern PFNGLINVALIDATEFRAMEBUFFERPROC                       gGLFunc_glInvalidateFramebuffer;
#define glInvalidateFramebuffer gGLFunc_glInvalidateFramebuffer
extern PFNGLINVALIDATESUBFRAMEBUFFERPROC                    gGLFunc_glInvalidateSubFramebuffer;
#define glInvalidateSubFramebuffer gGLFunc_glInvalidateSubFramebuffer
extern PFNGLMULTIDRAWARRAYSINDIRECTPROC                     gGLFunc_glMultiDrawArraysIndirect;
#define glMultiDrawArraysIndirect gGLFunc_glMultiDrawArraysIndirect
extern PFNGLMULTIDRAWELEMENTSINDIRECTPROC                   gGLFunc_glMultiDrawElementsIndirect;
#define glMultiDrawElementsIndirect gGLFunc_glMultiDrawElementsIndirect
extern PFNGLGETPROGRAMINTERFACEIVPROC                       gGLFunc_glGetProgramInterfaceiv;
#define glGetProgramInterfaceiv gGLFunc_glGetProgramInterfaceiv
extern PFNGLGETPROGRAMRESOURCEINDEXPROC                     gGLFunc_glGetProgramResourceIndex;
#define glGetProgramResourceIndex gGLFunc_glGetProgramResourceIndex
extern PFNGLGETPROGRAMRESOURCENAMEPROC                      gGLFunc_glGetProgramResourceName;
#define glGetProgramResourceName gGLFunc_glGetProgramResourceName
extern PFNGLGETPROGRAMRESOURCEIVPROC                        gGLFunc_glGetProgramResourceiv;
#define glGetProgramResourceiv gGLFunc_glGetProgramResourceiv
extern PFNGLGETPROGRAMRESOURCELOCATIONPROC                  gGLFunc_glGetProgramResourceLocation;
#define glGetProgramResourceLocation gGLFunc_glGetProgramResourceLocation
extern PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC             gGLFunc_glGetProgramResourceLocationIndex;
#define glGetProgramResourceLocationIndex gGLFunc_glGetProgramResourceLocationIndex
extern PFNGLSHADERSTORAGEBLOCKBINDINGPROC                   gGLFunc_glShaderStorageBlockBinding;
#define glShaderStorageBlockBinding gGLFunc_glShaderStorageBlockBinding
extern PFNGLTEXBUFFERRANGEPROC                              gGLFunc_glTexBufferRange;
#define glTexBufferRange gGLFunc_glTexBufferRange
extern PFNGLTEXSTORAGE2DMULTISAMPLEPROC                     gGLFunc_glTexStorage2DMultisample;
#define glTexStorage2DMultisample gGLFunc_glTexStorage2DMultisample
extern PFNGLTEXSTORAGE3DMULTISAMPLEPROC                     gGLFunc_glTexStorage3DMultisample;
#define glTexStorage3DMultisample gGLFunc_glTexStorage3DMultisample
extern PFNGLTEXTUREVIEWPROC                                 gGLFunc_glTextureView;
#define glTextureView gGLFunc_glTextureView
extern PFNGLBINDVERTEXBUFFERPROC                            gGLFunc_glBindVertexBuffer;
#define glBindVertexBuffer gGLFunc_glBindVertexBuffer
extern PFNGLVERTEXATTRIBFORMATPROC                          gGLFunc_glVertexAttribFormat;
#define glVertexAttribFormat gGLFunc_glVertexAttribFormat
extern PFNGLVERTEXATTRIBIFORMATPROC                         gGLFunc_glVertexAttribIFormat;
#define glVertexAttribIFormat gGLFunc_glVertexAttribIFormat
extern PFNGLVERTEXATTRIBLFORMATPROC                         gGLFunc_glVertexAttribLFormat;
#define glVertexAttribLFormat gGLFunc_glVertexAttribLFormat
extern PFNGLVERTEXATTRIBBINDINGPROC                         gGLFunc_glVertexAttribBinding;
#define glVertexAttribBinding gGLFunc_glVertexAttribBinding
extern PFNGLVERTEXBINDINGDIVISORPROC                        gGLFunc_glVertexBindingDivisor;
#define glVertexBindingDivisor gGLFunc_glVertexBindingDivisor
extern PFNGLDEBUGMESSAGECONTROLPROC                         gGLFunc_glDebugMessageControl;
#define glDebugMessageControl gGLFunc_glDebugMessageControl
extern PFNGLDEBUGMESSAGEINSERTPROC                          gGLFunc_glDebugMessageInsert;
#define glDebugMessageInsert gGLFunc_glDebugMessageInsert
extern PFNGLDEBUGMESSAGECALLBACKPROC                        gGLFunc_glDebugMessageCallback;
#define glDebugMessageCallback gGLFunc_glDebugMessageCallback
extern PFNGLGETDEBUGMESSAGELOGPROC                          gGLFunc_glGetDebugMessageLog;
#define glGetDebugMessageLog gGLFunc_glGetDebugMessageLog
extern PFNGLPUSHDEBUGGROUPPROC                              gGLFunc_glPushDebugGroup;
#define glPushDebugGroup gGLFunc_glPushDebugGroup
extern PFNGLPOPDEBUGGROUPPROC                               gGLFunc_glPopDebugGroup;
#define glPopDebugGroup gGLFunc_glPopDebugGroup
extern PFNGLOBJECTLABELPROC                                 gGLFunc_glObjectLabel;
#define glObjectLabel gGLFunc_glObjectLabel
extern PFNGLGETOBJECTLABELPROC                              gGLFunc_glGetObjectLabel;
#define glGetObjectLabel gGLFunc_glGetObjectLabel
extern PFNGLOBJECTPTRLABELPROC                              gGLFunc_glObjectPtrLabel;
#define glObjectPtrLabel gGLFunc_glObjectPtrLabel
extern PFNGLGETOBJECTPTRLABELPROC                           gGLFunc_glGetObjectPtrLabel;
#define glGetObjectPtrLabel gGLFunc_glGetObjectPtrLabel

// GL_VERSION_4_4
extern PFNGLBUFFERSTORAGEPROC       gGLFunc_glBufferStorage;
#define glBufferStorage gGLFunc_glBufferStorage
extern PFNGLCLEARTEXIMAGEPROC       gGLFunc_glClearTexImage;
#define glClearTexImage gGLFunc_glClearTexImage
extern PFNGLCLEARTEXSUBIMAGEPROC    gGLFunc_glClearTexSubImage;
#define glClearTexSubImage gGLFunc_glClearTexSubImage
extern PFNGLBINDBUFFERSBASEPROC     gGLFunc_glBindBuffersBase;
#define glBindBuffersBase gGLFunc_glBindBuffersBase
extern PFNGLBINDBUFFERSRANGEPROC    gGLFunc_glBindBuffersRange;
#define glBindBuffersRange gGLFunc_glBindBuffersRange
extern PFNGLBINDTEXTURESPROC        gGLFunc_glBindTextures;
#define glBindTextures gGLFunc_glBindTextures
extern PFNGLBINDSAMPLERSPROC        gGLFunc_glBindSamplers;
#define glBindSamplers gGLFunc_glBindSamplers
extern PFNGLBINDIMAGETEXTURESPROC   gGLFunc_glBindImageTextures;
#define glBindImageTextures gGLFunc_glBindImageTextures
extern PFNGLBINDVERTEXBUFFERSPROC   gGLFunc_glBindVertexBuffers;
#define glBindVertexBuffers gGLFunc_glBindVertexBuffers

// GL_VERSION_4_5
extern PFNGLCLIPCONTROLPROC                                     gGLFunc_glClipControl;
#define glClipControl gGLFunc_glClipControl
extern PFNGLCREATETRANSFORMFEEDBACKSPROC                        gGLFunc_glCreateTransformFeedbacks;
#define glCreateTransformFeedbacks gGLFunc_glCreateTransformFeedbacks
extern PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC                     gGLFunc_glTransformFeedbackBufferBase;
#define glTransformFeedbackBufferBase gGLFunc_glTransformFeedbackBufferBase
extern PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC                    gGLFunc_glTransformFeedbackBufferRange;
#define glTransformFeedbackBufferRange gGLFunc_glTransformFeedbackBufferRange
extern PFNGLGETTRANSFORMFEEDBACKIVPROC                          gGLFunc_glGetTransformFeedbackiv;
#define glGetTransformFeedbackiv gGLFunc_glGetTransformFeedbackiv
extern PFNGLGETTRANSFORMFEEDBACKI_VPROC                         gGLFunc_glGetTransformFeedbacki_v;
#define glGetTransformFeedbacki_v gGLFunc_glGetTransformFeedbacki_v
extern PFNGLGETTRANSFORMFEEDBACKI64_VPROC                       gGLFunc_glGetTransformFeedbacki64_v;
#define glGetTransformFeedbacki64_v gGLFunc_glGetTransformFeedbacki64_v
extern PFNGLCREATEBUFFERSPROC                                   gGLFunc_glCreateBuffers;
#define glCreateBuffers gGLFunc_glCreateBuffers
extern PFNGLNAMEDBUFFERSTORAGEPROC                              gGLFunc_glNamedBufferStorage;
#define glNamedBufferStorage gGLFunc_glNamedBufferStorage
extern PFNGLNAMEDBUFFERDATAPROC                                 gGLFunc_glNamedBufferData;
#define glNamedBufferData gGLFunc_glNamedBufferData
extern PFNGLNAMEDBUFFERSUBDATAPROC                              gGLFunc_glNamedBufferSubData;
#define glNamedBufferSubData gGLFunc_glNamedBufferSubData
extern PFNGLCOPYNAMEDBUFFERSUBDATAPROC                          gGLFunc_glCopyNamedBufferSubData;
#define glCopyNamedBufferSubData gGLFunc_glCopyNamedBufferSubData
extern PFNGLCLEARNAMEDBUFFERDATAPROC                            gGLFunc_glClearNamedBufferData;
#define glClearNamedBufferData gGLFunc_glClearNamedBufferData
extern PFNGLCLEARNAMEDBUFFERSUBDATAPROC                         gGLFunc_glClearNamedBufferSubData;
#define glClearNamedBufferSubData gGLFunc_glClearNamedBufferSubData
extern PFNGLMAPNAMEDBUFFERPROC                                  gGLFunc_glMapNamedBuffer;
#define glMapNamedBuffer gGLFunc_glMapNamedBuffer
extern PFNGLMAPNAMEDBUFFERRANGEPROC                             gGLFunc_glMapNamedBufferRange;
#define glMapNamedBufferRange gGLFunc_glMapNamedBufferRange
extern PFNGLUNMAPNAMEDBUFFERPROC                                gGLFunc_glUnmapNamedBuffer;
#define glUnmapNamedBuffer gGLFunc_glUnmapNamedBuffer
extern PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC                     gGLFunc_glFlushMappedNamedBufferRange;
#define glFlushMappedNamedBufferRange gGLFunc_glFlushMappedNamedBufferRange
extern PFNGLGETNAMEDBUFFERPARAMETERIVPROC                       gGLFunc_glGetNamedBufferParameteriv;
#define glGetNamedBufferParameteriv gGLFunc_glGetNamedBufferParameteriv
extern PFNGLGETNAMEDBUFFERPARAMETERI64VPROC                     gGLFunc_glGetNamedBufferParameteri64v;
#define glGetNamedBufferParameteri64v gGLFunc_glGetNamedBufferParameteri64v
extern PFNGLGETNAMEDBUFFERPOINTERVPROC                          gGLFunc_glGetNamedBufferPointerv;
#define glGetNamedBufferPointerv gGLFunc_glGetNamedBufferPointerv
extern PFNGLGETNAMEDBUFFERSUBDATAPROC                           gGLFunc_glGetNamedBufferSubData;
#define glGetNamedBufferSubData gGLFunc_glGetNamedBufferSubData
extern PFNGLCREATEFRAMEBUFFERSPROC                              gGLFunc_glCreateFramebuffers;
#define glCreateFramebuffers gGLFunc_glCreateFramebuffers
extern PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC                    gGLFunc_glNamedFramebufferRenderbuffer;
#define glNamedFramebufferRenderbuffer gGLFunc_glNamedFramebufferRenderbuffer
extern PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC                      gGLFunc_glNamedFramebufferParameteri;
#define glNamedFramebufferParameteri gGLFunc_glNamedFramebufferParameteri
extern PFNGLNAMEDFRAMEBUFFERTEXTUREPROC                         gGLFunc_glNamedFramebufferTexture;
#define glNamedFramebufferTexture gGLFunc_glNamedFramebufferTexture
extern PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC                    gGLFunc_glNamedFramebufferTextureLayer;
#define glNamedFramebufferTextureLayer gGLFunc_glNamedFramebufferTextureLayer
extern PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC                      gGLFunc_glNamedFramebufferDrawBuffer;
#define glNamedFramebufferDrawBuffer gGLFunc_glNamedFramebufferDrawBuffer
extern PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC                     gGLFunc_glNamedFramebufferDrawBuffers;
#define glNamedFramebufferDrawBuffers gGLFunc_glNamedFramebufferDrawBuffers
extern PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC                      gGLFunc_glNamedFramebufferReadBuffer;
#define glNamedFramebufferReadBuffer gGLFunc_glNamedFramebufferReadBuffer
extern PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC                  gGLFunc_glInvalidateNamedFramebufferData;
#define glInvalidateNamedFramebufferData gGLFunc_glInvalidateNamedFramebufferData
extern PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC               gGLFunc_glInvalidateNamedFramebufferSubData;
#define glInvalidateNamedFramebufferSubData gGLFunc_glInvalidateNamedFramebufferSubData
extern PFNGLCLEARNAMEDFRAMEBUFFERIVPROC                         gGLFunc_glClearNamedFramebufferiv;
#define glClearNamedFramebufferiv gGLFunc_glClearNamedFramebufferiv
extern PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC                        gGLFunc_glClearNamedFramebufferuiv;
#define glClearNamedFramebufferuiv gGLFunc_glClearNamedFramebufferuiv
extern PFNGLCLEARNAMEDFRAMEBUFFERFVPROC                         gGLFunc_glClearNamedFramebufferfv;
#define glClearNamedFramebufferfv gGLFunc_glClearNamedFramebufferfv
extern PFNGLCLEARNAMEDFRAMEBUFFERFIPROC                         gGLFunc_glClearNamedFramebufferfi;
#define glClearNamedFramebufferfi gGLFunc_glClearNamedFramebufferfi
extern PFNGLBLITNAMEDFRAMEBUFFERPROC                            gGLFunc_glBlitNamedFramebuffer;
#define glBlitNamedFramebuffer gGLFunc_glBlitNamedFramebuffer
extern PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC                     gGLFunc_glCheckNamedFramebufferStatus;
#define glCheckNamedFramebufferStatus gGLFunc_glCheckNamedFramebufferStatus
extern PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC                  gGLFunc_glGetNamedFramebufferParameteriv;
#define glGetNamedFramebufferParameteriv gGLFunc_glGetNamedFramebufferParameteriv
extern PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC        gGLFunc_glGetNamedFramebufferAttachmentParameteriv;
#define glGetNamedFramebufferAttachmentParameteriv gGLFunc_glGetNamedFramebufferAttachmentParameteriv
extern PFNGLCREATERENDERBUFFERSPROC                             gGLFunc_glCreateRenderbuffers;
#define glCreateRenderbuffers gGLFunc_glCreateRenderbuffers
extern PFNGLNAMEDRENDERBUFFERSTORAGEPROC                        gGLFunc_glNamedRenderbufferStorage;
#define glNamedRenderbufferStorage gGLFunc_glNamedRenderbufferStorage
extern PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC             gGLFunc_glNamedRenderbufferStorageMultisample;
#define glNamedRenderbufferStorageMultisample gGLFunc_glNamedRenderbufferStorageMultisample
extern PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC                 gGLFunc_glGetNamedRenderbufferParameteriv;
#define glGetNamedRenderbufferParameteriv gGLFunc_glGetNamedRenderbufferParameteriv
extern PFNGLCREATETEXTURESPROC                                  gGLFunc_glCreateTextures;
#define glCreateTextures gGLFunc_glCreateTextures
extern PFNGLTEXTUREBUFFERPROC                                   gGLFunc_glTextureBuffer;
#define glTextureBuffer gGLFunc_glTextureBuffer
extern PFNGLTEXTUREBUFFERRANGEPROC                              gGLFunc_glTextureBufferRange;
#define glTextureBufferRange gGLFunc_glTextureBufferRange
extern PFNGLTEXTURESTORAGE1DPROC                                gGLFunc_glTextureStorage1D;
#define glTextureStorage1D gGLFunc_glTextureStorage1D
extern PFNGLTEXTURESTORAGE2DPROC                                gGLFunc_glTextureStorage2D;
#define glTextureStorage2D gGLFunc_glTextureStorage2D
extern PFNGLTEXTURESTORAGE3DPROC                                gGLFunc_glTextureStorage3D;
#define glTextureStorage3D gGLFunc_glTextureStorage3D
extern PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC                     gGLFunc_glTextureStorage2DMultisample;
#define glTextureStorage2DMultisample gGLFunc_glTextureStorage2DMultisample
extern PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC                     gGLFunc_glTextureStorage3DMultisample;
#define glTextureStorage3DMultisample gGLFunc_glTextureStorage3DMultisample
extern PFNGLTEXTURESUBIMAGE1DPROC                               gGLFunc_glTextureSubImage1D;
#define glTextureSubImage1D gGLFunc_glTextureSubImage1D
extern PFNGLTEXTURESUBIMAGE2DPROC                               gGLFunc_glTextureSubImage2D;
#define glTextureSubImage2D gGLFunc_glTextureSubImage2D
extern PFNGLTEXTURESUBIMAGE3DPROC                               gGLFunc_glTextureSubImage3D;
#define glTextureSubImage3D gGLFunc_glTextureSubImage3D
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC                     gGLFunc_glCompressedTextureSubImage1D;
#define glCompressedTextureSubImage1D gGLFunc_glCompressedTextureSubImage1D
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC                     gGLFunc_glCompressedTextureSubImage2D;
#define glCompressedTextureSubImage2D gGLFunc_glCompressedTextureSubImage2D
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC                     gGLFunc_glCompressedTextureSubImage3D;
#define glCompressedTextureSubImage3D gGLFunc_glCompressedTextureSubImage3D
extern PFNGLCOPYTEXTURESUBIMAGE1DPROC                           gGLFunc_glCopyTextureSubImage1D;
#define glCopyTextureSubImage1D gGLFunc_glCopyTextureSubImage1D
extern PFNGLCOPYTEXTURESUBIMAGE2DPROC                           gGLFunc_glCopyTextureSubImage2D;
#define glCopyTextureSubImage2D gGLFunc_glCopyTextureSubImage2D
extern PFNGLCOPYTEXTURESUBIMAGE3DPROC                           gGLFunc_glCopyTextureSubImage3D;
#define glCopyTextureSubImage3D gGLFunc_glCopyTextureSubImage3D
extern PFNGLTEXTUREPARAMETERFPROC                               gGLFunc_glTextureParameterf;
#define glTextureParameterf gGLFunc_glTextureParameterf
extern PFNGLTEXTUREPARAMETERFVPROC                              gGLFunc_glTextureParameterfv;
#define glTextureParameterfv gGLFunc_glTextureParameterfv
extern PFNGLTEXTUREPARAMETERIPROC                               gGLFunc_glTextureParameteri;
#define glTextureParameteri gGLFunc_glTextureParameteri
extern PFNGLTEXTUREPARAMETERIIVPROC                             gGLFunc_glTextureParameterIiv;
#define glTextureParameterIiv gGLFunc_glTextureParameterIiv
extern PFNGLTEXTUREPARAMETERIUIVPROC                            gGLFunc_glTextureParameterIuiv;
#define glTextureParameterIuiv gGLFunc_glTextureParameterIuiv
extern PFNGLTEXTUREPARAMETERIVPROC                              gGLFunc_glTextureParameteriv;
#define glTextureParameteriv gGLFunc_glTextureParameteriv
extern PFNGLGENERATETEXTUREMIPMAPPROC                           gGLFunc_glGenerateTextureMipmap;
#define glGenerateTextureMipmap gGLFunc_glGenerateTextureMipmap
extern PFNGLBINDTEXTUREUNITPROC                                 gGLFunc_glBindTextureUnit;
#define glBindTextureUnit gGLFunc_glBindTextureUnit
extern PFNGLGETTEXTUREIMAGEPROC                                 gGLFunc_glGetTextureImage;
#define glGetTextureImage gGLFunc_glGetTextureImage
extern PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC                       gGLFunc_glGetCompressedTextureImage;
#define glGetCompressedTextureImage gGLFunc_glGetCompressedTextureImage
extern PFNGLGETTEXTURELEVELPARAMETERFVPROC                      gGLFunc_glGetTextureLevelParameterfv;
#define glGetTextureLevelParameterfv gGLFunc_glGetTextureLevelParameterfv
extern PFNGLGETTEXTURELEVELPARAMETERIVPROC                      gGLFunc_glGetTextureLevelParameteriv;
#define glGetTextureLevelParameteriv gGLFunc_glGetTextureLevelParameteriv
extern PFNGLGETTEXTUREPARAMETERFVPROC                           gGLFunc_glGetTextureParameterfv;
#define glGetTextureParameterfv gGLFunc_glGetTextureParameterfv
extern PFNGLGETTEXTUREPARAMETERIIVPROC                          gGLFunc_glGetTextureParameterIiv;
#define glGetTextureParameterIiv gGLFunc_glGetTextureParameterIiv
extern PFNGLGETTEXTUREPARAMETERIUIVPROC                         gGLFunc_glGetTextureParameterIuiv;
#define glGetTextureParameterIuiv gGLFunc_glGetTextureParameterIuiv
extern PFNGLGETTEXTUREPARAMETERIVPROC                           gGLFunc_glGetTextureParameteriv;
#define glGetTextureParameteriv gGLFunc_glGetTextureParameteriv
extern PFNGLCREATEVERTEXARRAYSPROC                              gGLFunc_glCreateVertexArrays;
#define glCreateVertexArrays gGLFunc_glCreateVertexArrays
extern PFNGLDISABLEVERTEXARRAYATTRIBPROC                        gGLFunc_glDisableVertexArrayAttrib;
#define glDisableVertexArrayAttrib gGLFunc_glDisableVertexArrayAttrib
extern PFNGLENABLEVERTEXARRAYATTRIBPROC                         gGLFunc_glEnableVertexArrayAttrib;
#define glEnableVertexArrayAttrib gGLFunc_glEnableVertexArrayAttrib
extern PFNGLVERTEXARRAYELEMENTBUFFERPROC                        gGLFunc_glVertexArrayElementBuffer;
#define glVertexArrayElementBuffer gGLFunc_glVertexArrayElementBuffer
extern PFNGLVERTEXARRAYVERTEXBUFFERPROC                         gGLFunc_glVertexArrayVertexBuffer;
#define glVertexArrayVertexBuffer gGLFunc_glVertexArrayVertexBuffer
extern PFNGLVERTEXARRAYVERTEXBUFFERSPROC                        gGLFunc_glVertexArrayVertexBuffers;
#define glVertexArrayVertexBuffers gGLFunc_glVertexArrayVertexBuffers
extern PFNGLVERTEXARRAYATTRIBBINDINGPROC                        gGLFunc_glVertexArrayAttribBinding;
#define glVertexArrayAttribBinding gGLFunc_glVertexArrayAttribBinding
extern PFNGLVERTEXARRAYATTRIBFORMATPROC                         gGLFunc_glVertexArrayAttribFormat;
#define glVertexArrayAttribFormat gGLFunc_glVertexArrayAttribFormat
extern PFNGLVERTEXARRAYATTRIBIFORMATPROC                        gGLFunc_glVertexArrayAttribIFormat;
#define glVertexArrayAttribIFormat gGLFunc_glVertexArrayAttribIFormat
extern PFNGLVERTEXARRAYATTRIBLFORMATPROC                        gGLFunc_glVertexArrayAttribLFormat;
#define glVertexArrayAttribLFormat gGLFunc_glVertexArrayAttribLFormat
extern PFNGLVERTEXARRAYBINDINGDIVISORPROC                       gGLFunc_glVertexArrayBindingDivisor;
#define glVertexArrayBindingDivisor gGLFunc_glVertexArrayBindingDivisor
extern PFNGLGETVERTEXARRAYIVPROC                                gGLFunc_glGetVertexArrayiv;
#define glGetVertexArrayiv gGLFunc_glGetVertexArrayiv
extern PFNGLGETVERTEXARRAYINDEXEDIVPROC                         gGLFunc_glGetVertexArrayIndexediv;
#define glGetVertexArrayIndexediv gGLFunc_glGetVertexArrayIndexediv
extern PFNGLGETVERTEXARRAYINDEXED64IVPROC                       gGLFunc_glGetVertexArrayIndexed64iv;
#define glGetVertexArrayIndexed64iv gGLFunc_glGetVertexArrayIndexed64iv
extern PFNGLCREATESAMPLERSPROC                                  gGLFunc_glCreateSamplers;
#define glCreateSamplers gGLFunc_glCreateSamplers
extern PFNGLCREATEPROGRAMPIPELINESPROC                          gGLFunc_glCreateProgramPipelines;
#define glCreateProgramPipelines gGLFunc_glCreateProgramPipelines
extern PFNGLCREATEQUERIESPROC                                   gGLFunc_glCreateQueries;
#define glCreateQueries gGLFunc_glCreateQueries
extern PFNGLGETQUERYBUFFEROBJECTI64VPROC                        gGLFunc_glGetQueryBufferObjecti64v;
#define glGetQueryBufferObjecti64v gGLFunc_glGetQueryBufferObjecti64v
extern PFNGLGETQUERYBUFFEROBJECTIVPROC                          gGLFunc_glGetQueryBufferObjectiv;
#define glGetQueryBufferObjectiv gGLFunc_glGetQueryBufferObjectiv
extern PFNGLGETQUERYBUFFEROBJECTUI64VPROC                       gGLFunc_glGetQueryBufferObjectui64v;
#define glGetQueryBufferObjectui64v gGLFunc_glGetQueryBufferObjectui64v
extern PFNGLGETQUERYBUFFEROBJECTUIVPROC                         gGLFunc_glGetQueryBufferObjectuiv;
#define glGetQueryBufferObjectuiv gGLFunc_glGetQueryBufferObjectuiv
extern PFNGLMEMORYBARRIERBYREGIONPROC                           gGLFunc_glMemoryBarrierByRegion;
#define glMemoryBarrierByRegion gGLFunc_glMemoryBarrierByRegion
extern PFNGLGETTEXTURESUBIMAGEPROC                              gGLFunc_glGetTextureSubImage;
#define glGetTextureSubImage gGLFunc_glGetTextureSubImage
extern PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC                    gGLFunc_glGetCompressedTextureSubImage;
#define glGetCompressedTextureSubImage gGLFunc_glGetCompressedTextureSubImage
extern PFNGLGETGRAPHICSRESETSTATUSPROC                          gGLFunc_glGetGraphicsResetStatus;
#define glGetGraphicsResetStatus gGLFunc_glGetGraphicsResetStatus
extern PFNGLGETNCOMPRESSEDTEXIMAGEPROC                          gGLFunc_glGetnCompressedTexImage;
#define glGetnCompressedTexImage gGLFunc_glGetnCompressedTexImage
extern PFNGLGETNTEXIMAGEPROC                                    gGLFunc_glGetnTexImage;
#define glGetnTexImage gGLFunc_glGetnTexImage
extern PFNGLGETNUNIFORMDVPROC                                   gGLFunc_glGetnUniformdv;
#define glGetnUniformdv gGLFunc_glGetnUniformdv
extern PFNGLGETNUNIFORMFVPROC                                   gGLFunc_glGetnUniformfv;
#define glGetnUniformfv gGLFunc_glGetnUniformfv
extern PFNGLGETNUNIFORMIVPROC                                   gGLFunc_glGetnUniformiv;
#define glGetnUniformiv gGLFunc_glGetnUniformiv
extern PFNGLGETNUNIFORMUIVPROC                                  gGLFunc_glGetnUniformuiv;
#define glGetnUniformuiv gGLFunc_glGetnUniformuiv
extern PFNGLREADNPIXELSPROC                                     gGLFunc_glReadnPixels;
#define glReadnPixels gGLFunc_glReadnPixels
extern PFNGLGETNMAPDVPROC                                       gGLFunc_glGetnMapdv;
#define glGetnMapdv gGLFunc_glGetnMapdv
extern PFNGLGETNMAPFVPROC                                       gGLFunc_glGetnMapfv;
#define glGetnMapfv gGLFunc_glGetnMapfv
extern PFNGLGETNMAPIVPROC                                       gGLFunc_glGetnMapiv;
#define glGetnMapiv gGLFunc_glGetnMapiv
extern PFNGLGETNPIXELMAPFVPROC                                  gGLFunc_glGetnPixelMapfv;
#define glGetnPixelMapfv gGLFunc_glGetnPixelMapfv
extern PFNGLGETNPIXELMAPUIVPROC                                 gGLFunc_glGetnPixelMapuiv;
#define glGetnPixelMapuiv gGLFunc_glGetnPixelMapuiv
extern PFNGLGETNPIXELMAPUSVPROC                                 gGLFunc_glGetnPixelMapusv;
#define glGetnPixelMapusv gGLFunc_glGetnPixelMapusv
extern PFNGLGETNPOLYGONSTIPPLEPROC                              gGLFunc_glGetnPolygonStipple;
#define glGetnPolygonStipple gGLFunc_glGetnPolygonStipple
extern PFNGLGETNCOLORTABLEPROC                                  gGLFunc_glGetnColorTable;
#define glGetnColorTable gGLFunc_glGetnColorTable
extern PFNGLGETNCONVOLUTIONFILTERPROC                           gGLFunc_glGetnConvolutionFilter;
#define glGetnConvolutionFilter gGLFunc_glGetnConvolutionFilter
extern PFNGLGETNSEPARABLEFILTERPROC                             gGLFunc_glGetnSeparableFilter;
#define glGetnSeparableFilter gGLFunc_glGetnSeparableFilter
extern PFNGLGETNHISTOGRAMPROC                                   gGLFunc_glGetnHistogram;
#define glGetnHistogram gGLFunc_glGetnHistogram
extern PFNGLGETNMINMAXPROC                                      gGLFunc_glGetnMinmax;
#define glGetnMinmax gGLFunc_glGetnMinmax
extern PFNGLTEXTUREBARRIERPROC                                  gGLFunc_glTextureBarrier;
#define glTextureBarrier gGLFunc_glTextureBarrier

// GL_VERSION_4_6
extern PFNGLSPECIALIZESHADERPROC                gGLFunc_glSpecializeShader;
#define glSpecializeShader gGLFunc_glSpecializeShader
extern PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC    gGLFunc_glMultiDrawArraysIndirectCount;
#define glMultiDrawArraysIndirectCount gGLFunc_glMultiDrawArraysIndirectCount
extern PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC  gGLFunc_glMultiDrawElementsIndirectCount;
#define glMultiDrawElementsIndirectCount gGLFunc_glMultiDrawElementsIndirectCount
extern PFNGLPOLYGONOFFSETCLAMPPROC              gGLFunc_glPolygonOffsetClamp;
#define glPolygonOffsetClamp gGLFunc_glPolygonOffsetClamp

#endif // LL_GLFUNCTIONDECLS_H
